### ISSUE TITLE
Feature: 建议onebot增加直接发图片文件的模式

### ISSUE THREAD

**Issue by kuyin** [koishijs/novelai-bot#100]
### Scope

NovelAI, NAIFU, Stable Diffusion WebUI (AUTOMATIC1111), Others

### Describe the problem related to the feature request

由于qq压缩画质过于严重，出来的图片已经糊成一片，448×832的图片只有不到100kb
![2127242D-8972-426B-A3D4-D2F5F2AF4C53](https://user-images.githubusercontent.com/7321275/200229495-0fa7189e-fcee-4471-9b44-b51a1766b4f0.png)

### Describe the solution you'd like

是否可以加一个直接传图片文件的模式，避免qq对图片的压缩呢？

**Comment by MaikoTan** [comment]
Hello, @kuyin 
There is already an option named "output", you can set it as "minimum".

你好, @kuyin 
已经有一个选项叫做“输出”，你可以设置它为“最小值”。

**Comment by MirrorCY** [comment]
I think he meant to send png files, not jpg, maybe the point is not on single images.

我觉得他的意思是发送原始 png 文件，而不是 jpg 图片，也许重点不在单张图片。

**Comment by MaikoTan** [comment]
I think most people using `go-cqhttp` as the backend onebot, right?
According to their doc, the PNG file should be sent without compressing, or am I wrong?

> PNG format will not be compressed, JPG may not be compressed twice, GIF non-moving image is converted to PNG

_From https://docs.go-cqhttp.org/cqcode/#%E5%9B%BE%E7%89%87_

As for sending images as file, there would be issues nouveau on it. Like "Only group manager and administrator could upload files", or "There isn't any more spaces to store your uploaded files", or even the uploaded file became blank.
I don't think it can be the solution for that.

If you are focus on the quality, you should use the NovelAI website instead, as they even provide high resolutions that you can't even upload them via onebot.

------

我想大多数人使用`go-cqhttp`作为后端onebot，对吗？
根据他们的文档，PNG文件应该是不压缩发送的，还是我错了？

> PNG格式不会被压缩，JPG可能不会被压缩两次，GIF非移动图像被转换为PNG

_From https://docs.go-cqhttp.org/cqcode/#%E5%9B%BE%E7%89%87_

至于以文件形式发送图片，会有问题新的上。比如 "只有小组经理和管理员可以上传文件"，或者 "没有更多的空间来存储你上传的文件"，甚至上传的文件变成空白。
我不认为它是解决这个问题的办法。

如果你注重质量，你应该使用NovelAI网站，因为他们甚至提供高分辨率，你不能通过onebot上传他们。

**Comment by shigma** [comment]
这应该不是发送端的问题，而是接收端。根据我的观察，部分 naibot 生成的图片仍然可以被以 png 格式下载。很可能这跟你的 QQ 客户端有关。

![image](https://user-images.githubusercontent.com/33423008/200236369-feb617b9-a566-4dc2-9bd6-4ae9ce1b9a3a.png)

上面是我刚刚用 PC TIM 约稿并下载的效果图，可以看到格式是正确的。

**Comment by kuyin** [comment]
调查清楚了，是mobile qq版本自动压缩了png图片，pc version是正常的

**Comment by MaikoTan** [comment]
Sure. So we can't do anything for it.

好的。所以我们无法对它做任何事情。
