### ISSUE TITLE
Bug: 法语帮助信息翻译不完全

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/novelai-bot#101]
### Describe the bug

法语帮助信息翻译不完全，存在部分中文

### Steps to reproduce

1. user.locale fr
2. nai -h

### Expected behavior

法语帮助信息翻译完全

### Screenshots

![image](https://user-images.githubusercontent.com/37006258/200458429-e9df37a3-bb0c-46a8-96f1-4daf56201ec2.png)

### Launcher

Containers (Docker, Kubernates, etc)

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- Koishi version: 4.9.9

**Comment by MaikoTan** [comment]
Il semble qu'il y en ait deux qui ne sont pas traduits (`override` et `undesired`).
J'y travaillerais plus tard. Merci beaucoup de l'avoir.

**Comment by MaikoTan** [comment]
Qu'en est-il des "Remplacer les descriptions textuelles de base" et "Définir les descriptions textuelles négatives" ?

**Comment by MirrorCY** [comment]
As a non-French user, according to the translation software, it seems good.  ;  )
