### ISSUE TITLE
Bug: novelai中授权令牌的参数设置默认不包含model导致报错

### ISSUE THREAD

**Issue by medicago087** [koishijs/novelai-bot#113]
### Describe the bug

novelai中token的参数设置默认不包含model，直接使用导致报错：发生未知错误 (400)。
切换成账号密码再切回token才能成功显示，解决问题。

### Steps to reproduce

安装koishi desktop0.8.1，安装novelai，默认参数设置第一行为sampler而不含model，使用时报错400。
登录方式切换为账号密码再切换成授权令牌，model: nai出现，可以正常使用。

### Expected behavior

参数设置第一行为model: nai

### Screenshots

![0$4ZM5 `4R5L%22EO~_}S3K](https://user-images.githubusercontent.com/68104673/201075953-cb128c09-f687-42aa-b2af-9c5d4922abe6.png)
![EC7_TUM8BJOD}CAM)$QHNWA](https://user-images.githubusercontent.com/68104673/201075978-c1ace33f-a011-4c39-9873-22196ee8993f.png)

### Launcher

Koishi Desktop

### Backend

NovelAI (Token)

### Versions

win server2019 & android

**Comment by MaikoTan** [comment]
Quelle version de `koishi` et `@koishijs/plugin-console` vous vous utilisez ?
Ils sont tous mis à jour au plus tard ?

------

你使用的是什么版本的 `koishi` 和 `@koishijs/plugin-console`？

他们都是最新的吗？

**Comment by medicago087** [comment]
复现用的0.8.1msi，看了一下是4.10.0最新的koishi和4.6.10的console

**Comment by MirrorCY** [comment]
#112 已更新文档，针对该问题给出了解决方案

**Comment by shigma** [comment]
这问题现在还存在吗？

**Comment by medicago087** [comment]
仍然存在。
![image](https://user-images.githubusercontent.com/68104673/204979893-ec89ad78-6c3e-403a-938c-81963b5b297f.png)
![image](https://user-images.githubusercontent.com/68104673/204979894-6f3cda8d-2a78-4608-8c67-616cc76c0197.png)

**Comment by MaikoTan** [comment]
Still reproducible in the `koishi v4.11.4` and `plugin-console v5.2.1`.

**Comment by MirrorCY** [comment]
Finally, it was resolved. although we still dont know which version fixed it, the problem no longer reproduces with Koishi 4.16.8 and nai 1.20.1
