### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by Z-fly** [koishijs/novelai-bot#12]
![image](https://user-images.githubusercontent.com/10470892/194740627-23dee0b7-7669-43ad-8737-9a0f9d429cd1.png)

**Comment by shigma** [comment]
安装失败可以尝试重启。

**Comment by Z-fly** [comment]
装好了，请问授权令牌在哪里看？

**Comment by shigma** [comment]
https://github.com/koishijs/novelai-bot#token

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/194742120-08122099-01c5-4075-8352-6b2b1c6456e4.png)
orient没有生效吗？我要生成横的图

**Comment by shigma** [comment]
横的是 landscape，竖的是 portrait
