### ISSUE TITLE
Feature: Add a Option to Disable Translator in One Command Invocation

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/novelai-bot#122]
### Scope

NovelAI, NAIFU, Stable Diffusion WebUI (AUTOMATIC1111), Others

### Describe the problem related to the feature request

Per https://github.com/koishijs/novelai-bot/issues/58#issuecomment-1321053138

### Describe the solution you'd like

1. Add a new option says `--disable-translate` (maybe there's better naming)
2. If no translator available or `config.translator` is false, ignore it.
3. If translator(s) available and `config.translator` is true
  3.1 If the option in 1) is false, translate the prompt
  3.2 If the option in 1) is true, not translate the prompt

### Describe alternatives you've considered

As https://github.com/koishijs/novelai-bot/issues/117
Disable translate there are only English words.

**Comment by shigma** [comment]
Is there another requirement to manually enable translation when `config.translator` is set to `false`?

**Comment by MaikoTan** [comment]
I didn't know there are. So I shamefully assume the answer is no.
Most reports pointed out that the translators always get you a false result.

When the user is trying generate wonderful pictures, they would usually use English words and don't want their prompt to be messed up by the baka translator.
On the other hand (no offense by the way), when user is using another language to describe their image, it would be more like playing.
