### ISSUE TITLE
Feature: Any plan to the implement of the --noise feature?

### ISSUE THREAD

**Issue by kuyin** [koishijs/novelai-bot#127]
### Scope

NovelAI, NAIFU, Stable Diffusion WebUI (AUTOMATIC1111), Others

### Describe the problem related to the feature request

i2i need another dimension to control the noise which you already listed in the help menu but with no real function now.
Any plan for this in the near future?

### Describe the solution you'd like

--noise

### Describe alternatives you've considered

no

### Additional context

no

**Comment by MaikoTan** [comment]
`noise` parameter was effective in NovelAI and NAIFU, but afaik it looks like there is no a proper parameter in SD-WebUI that correspond to the `noise` parameter, so I didn't implement it.

`noise` 参数在 NovelAI 和 NAIFU 中是有效的，但阿弗艾克看起来，在 SD-WebUI 中没有一个合适的参数对应于 `noise` 参数，所以我没有实现它。

**Comment by MaikoTan** [comment]
If you do know there IS a parameter in Stable Diffusion Web UI that controls the things same as `noise` in Novel AI, please tell me.
Or I'll close this issue as not planned.

如果你知晓那里有一个参数在稳定扩散网页用户界面中控制了与小说人工智能同样的东西们，请告诉我。
或者我会关闭这个议题作为未计划的。

**Comment by MaikoTan** [comment]
As this feature seems not able to be implemented, and is stale over a month.
I'll close this issue as not planned, if anyone has extra comments, just open a new one.

由于这个功能不可能被实现，并且闲置超过一个月。
会关闭这个议题作为未计划的，如果你有额外的评论，只是开启一个新的。
