### ISSUE TITLE
我拥有了一个必定风控导致卡死bug稳定触发的QQ账号 | 测试经验分享

### ISSUE THREAD

**Issue by wlz-remake** [koishijs/novelai-bot#129]
登录方式：sd-webui
系统：Windows server 2019
版本：Koishi Desktop v0.8.1
（截至2022年11月21日23点32分，所有依赖已更新至最新）

通过向上百个群同时发送同一条消息，使QQ账号无法再发送群消息
![D6949606A45EB0DAE60A3DD90CE13AE0](https://user-images.githubusercontent.com/105090141/203099906-0baebdde-5c11-4736-a4bb-bcee309713b0.jpg)

输出方式设置为“发送全部信息”，在群聊中发送【约稿 miku】，可观察到web控制台日志中出现了两次“消息被风控”的报告，第一次是“少女绘画中...”的风控，第二次即约稿结果的合并消息，随后Koishi卡死。**但在重启后，第二次风控的报告消失不见。**
卡死时最后的全部日志：
![image](https://user-images.githubusercontent.com/105090141/203100289-5bd2c515-c961-44b8-a8a3-366c01861959.png)
重启后的日志：
![4JFPQIOX` QGL(OO3VVP_ T](https://user-images.githubusercontent.com/105090141/203099310-35448226-0a5e-42df-a7b6-1e749a9a6e5b.png)
将输出方式设置为“只发送图片”，情况不变

怀疑是卡死在了logger，遂将此插件关闭，但问题并未解决，情况仍和原来一样

按照 https://k.ilharp.cc/r7 里的方法尝试高级诊断，但触发bug后没有日志输出/悲
![SXAC51Z3G7 %VC2 @X`D49I](https://user-images.githubusercontent.com/105090141/203101848-ae9f61c2-d99c-4cd3-badd-4221d950b1a7.jpg)
![F5SAI$V_LO(K2M{YS}W@(T](https://user-images.githubusercontent.com/105090141/203101883-ed274770-5c8c-4c18-898e-7499170c8710.jpg)

用echo在群聊中让bot（在被风控的情况下）尝试发图，虽然图片仍然发不出来，但web控制台日志中有风控报告且**没有卡死**

改用基于 [novelai-bot](https://github.com/koishijs/novelai-bot) 修改完成，使用 [stablehorde](https://stablehorde.net/) 进行 AI 图片生成的插件 [rryth](https://github.com/MirrorCY/rryth) ，bot同样被风控但**没有卡死**

关闭sd-webui设置中的“将有关生成参数的文本信息，作为块保存到 png 图片文件中”，**bot卡死**

所以现在貌似就novelai-bot插件会导致风控下发图卡死？

**Comment by shigma** [comment]
可以尝试使用外置 gocq 复现吗？具体步骤如下：

1. 关闭 gocqhttp 插件
2. 进入 accounts/123456789 目录直接运行 ./go-cqhttp（替换为你的 QQ 号）
3. 重载 onebot 插件
4. 尝试图片生成并发送，检查是否卡死

**Comment by shigma** [comment]
问题基本上确定了，非常感谢你提供的珍贵线索！
