### ISSUE TITLE
想搭在公网上供大众使用，请问有没有办法隐藏插件配置？

### ISSUE THREAD

**Issue by Z-fly** [koishijs/novelai-bot#13]

**Comment by NWYLZW** [comment]
暂时好像不太合适将 webui 放到公网上
你可以在 koishi console 的 repo 说说你想要的具体权限功能
（如果你说的公网上给大众使用指的是 webui 的话）

**Comment by shigma** [comment]
如果你说的是控制台的话，可以加装 database 和 auth 插件。

先装 database 并给自己高级权限，然后装 auth 限制低权限者对插件配置的访问。

**Comment by shigma** [comment]
1. 安装任意 database 插件（首选 mysql / mongo，其次建议 sqlite）
2. 在群里发言，此时机器人会自动帮你创建用户数据
3. 启动 dataview 插件，在网页中找到自己的数据并将 authority 设置为 4 或者更高
4. 安装并启用 auth 插件

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/194752859-338cb929-707a-4da3-8166-8ed2cd867be5.png)
不知道这个地方要填什么了 然后重装完也无法改配置了 用的是sqlite

**Comment by shigma** [comment]
如果你已经完成 1-3 步，那么平台名输入 onebot，账号输入你的 QQ 号；

如果未完成第 3 步，你需要手动开配置文件关闭 auth 插件后重启完成第 3 步后继续。

PS：这个流程确实有点复杂，未来我们会直接创建一个管理员账号的。

**Comment by Z-fly** [comment]
配置文件在哪里？

**Comment by shigma** [comment]
C:/Users/你的用户名/AppData/Roaming/Il Harper/Koishi/data/instances/default/koishi.yml

找到以后把 `auth` 改成 `~auth`

**Comment by Z-fly** [comment]
如何创建用户名和密码？

**Comment by shigma** [comment]
等下你有安装适配器吗，接入 QQ  之类？

**Comment by shigma** [comment]
哦你是不是想直接把沙盒当成 stable diffusion 的 webui 用？

**Comment by Z-fly** [comment]
对，是的。想让大家直接用了

**Comment by shigma** [comment]
抱歉，我们做的时候还没考虑到有这种需求……现在应该是做不到的（技术层面完全没有问题，但是 UI 上缺乏相关的设计）。

如果您愿意等几天的话我会完善一下这个流程。

**Comment by Z-fly** [comment]
好的，谢谢。

**Comment by Baninn** [comment]
stable diffusion可以添加--share参数，接入gradio.app获得一个72h有效的公网链接，可以直接在外网访问。不知道是不是你需要的

**Comment by Z-fly** [comment]
> stable diffusion可以添加--share参数，接入gradio.app获得一个72h有效的公网链接，可以直接在外网访问。不知道是不是你需要的

novelai买了订阅后，普通参数生成图片可以无限次数用，不消耗Anlas，所以是这样考虑的

**Comment by shigma** [comment]
最新版本已经实现了自动创建管理员账户的功能。

如果启动时不存在高于 4 级的账户，则会自动创建一个管理员：admin/123456。
