### ISSUE TITLE
Feature: update plugin description in manifest

### ISSUE THREAD

**Issue by shigma** [koishijs/novelai-bot#136]
> Generate images by [NovelAI](https://novelai.net/)

should be changed into something like

> Generate images by NovelAI / Stable Diffusion / more

@MaikoTan

**Comment by MaikoTan** [comment]
As it is mendo-sugi don't want to open a new PR. So I just comment here.

en : `Generate images by NovelAI / Stable Diffusion / more`
fr : `Générer Générer des images sur NovelAI / Stable Diffusion / more`
zh : `基于 NovelAI、Stable Diffusion 等的画图插件`
zh-tw : `基於 NovelAI、Stable Diffusion 等的畫圖插件`
ja : `NovelAI や Stable Diffusion などに基づいて画像を生成する`
