### ISSUE TITLE
Feature: 添加更多参数设置

### ISSUE THREAD

**Issue by medicago087** [koishijs/novelai-bot#137]
### Scope

NovelAI, NAIFU, Stable Diffusion WebUI (AUTOMATIC1111)

### Describe the problem related to the feature request

参数设置中目前有默认的图片方向，还想要设置默认的图片分辨率、迭代步数

### Describe the solution you'd like

添加默认的图片分辨率、默认的迭代步数。如果可以，为sd添加图片保存到本地开关（为了收集群友xp）

**Comment by MaikoTan** [comment]
The orientation and the resolution of an image are the same thing, so we can just extend the orientation configuration for it.
The iteration step seems worth to be a configuration here, would add later.

一张图片的朝向和分辨率是同一个东西，所以我们可以只是扩展方向配置为了它。
遍历脚步感觉值得作为一个配置在这里，之后会增加它。
