### ISSUE TITLE
更新后出现图片解析错误

### ISSUE THREAD

**Issue by wuwo020** [koishijs/novelai-bot#144]
### Describe the bug

koishi更新4.10.4后，将novelai插件升级1.15.1后url解析出现错误导致无法解析图片
（可能附带的其他问题，-T --strength 指令无法生效，不排除是图片解析失败后无法调用）

### Steps to reproduce

好问题，其实我也不知道，跟群友讨论后，大概率更新kshio4.10.4或者新版本ai插件后都有概率出现此问题，目前已经发现三例（群内）

### Expected behavior

修复此bug

### Relevant log output

```shell
日志输出正常
```

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version:

**Comment by MirrorCY** [comment]
问题已稳定复现，当使用关键词 `约稿` 进行图转图时，图片解析异常。使用关键词 `nai` 时，一切正常。
***
This issue has been confirmed. When using the keyword '约稿' for i2i, the bug has reappeared.​ When using the keyword 'nai', everything is fine. @MaikoTan

**Comment by MaikoTan** [comment]
Then it might be lead to the changes recently about `shortcut` by @shigma .

**Comment by shigma** [comment]
--strength 实际上是生效了的，只不过没有显示，问题出在图片解析上。

**Comment by shigma** [comment]
4.10.5 已修复。
