### ISSUE TITLE
Feature:  能不能修改唤醒ai功能的关键字 比如约稿改成画图

### ISSUE THREAD

**Issue by yulongyu** [koishijs/novelai-bot#148]
### Scope

Stable Diffusion WebUI (AUTOMATIC1111)

### Describe the problem related to the feature request

我想改一下呼叫ai功能的关键字，比如约稿改成画图，能否通过代码内部某个文件来修改？

### Describe the solution you'd like

如果没法配置，我是否能通过修改内部js代码来解决这个问题？还是说这些东西是加密了的无法改？

### Describe alternatives you've considered

无

### Additional context

无

**Comment by MaikoTan** [comment]
I think you cannot "change" the keyword, but you could add an alias for the command.

- First, you should install `commands` plugin from the plugin market.
- Then, enter "novelai" in the first line in the `commands` plugin configuration page.
- Down to `alias`, tap `Add` and enter `画图` or anything you like.
- Finally, enable the `commands` plugin.

我认为你不能“改变”关键字，但你可以为命令添加一个别名。

 - 首先，您应该从插件市场安装 `commands` 插件。
 - 然后，在`commands` 插件配置页面的第一行输入“novelai”。
 - 在“别名”下方，点击“添加”并输入“画图”或您喜欢的任何内容。
 - 最后，启用 `commands` 插件。

**Comment by yulongyu** [comment]
> * 画图

可以是可以，不过里面的配置多个别名，只能生效一个，下面的那些参数有啥含义么 比如create和hiden

**Comment by shigma** [comment]
@yulongyu 首先我们现在不仅支持「约稿」还支持「画画」，你看是否满足你的需求。

其次你要改的东西实际上叫 shortcut，我开了一个 PR #141 将允许用户修改这些名字。

最后上面 @MaikoTan 介绍的方法也是可用的。

**Comment by shigma** [comment]
i18n shortcut 已经支持！现在可以在 locales 页面修改关键字了！
