### ISSUE TITLE
小白能否问下挂载qq上显示这个，无法使用。

### ISSUE THREAD

**Issue by TCfeiyu** [koishijs/novelai-bot#15]
按照教程的设置完后点击启动弹出一系列这个框
![LRS_%~99`2)@7JI@OF`0W{I](https://user-images.githubusercontent.com/102469592/194746396-01f7ce02-73b3-4f43-b2f6-35361da112bc.png)
然后在account文件中找到了bat文件。
但是双击后却显示这个
![E)B_4S7D6JJ7)HOE )R7XKM](https://user-images.githubusercontent.com/102469592/194746435-e73c270b-9280-4779-8092-e711301d2519.png)
请问是我哪里没设置好吗。有什么办法解决吗。

**Comment by shigma** [comment]
你并没有按照教程进行。Koishi 并不会弹这个框。

**Comment by TCfeiyu** [comment]
> 你并没有按照教程进行100 . Koishi并不会弹这个框。

我是按照快速搭建这个步骤来的。

如果想进一步在 QQ 中使用，可继续进行下列操作：

准备一个 QQ 号 (等级不要过低，否则可能被风控)
点击左侧的「插件配置」，选择「onebot」插件，完成以下配置：
在「selfId」填写你的 QQ 号
在「password」填写你的密码
在「protocol」选择 ws-reverse
开启「gocqhttp.enable」选项
点击右上角的「启用」按钮
现在你可以在 QQ 上中使用画图功能了！

完全按照这个步骤进行的操作。
是需要看别的教程吗。还是插件命不一样？我用的adapter-onebot。

**Comment by shigma** [comment]
问了一下，这个弹框是 go-cqhttp 自带的，但是得双击 exe 文件才有。我再去研究一下。

**Comment by Nomelande** [comment]
#16 他遇到的应该也是这个问题

**Comment by shigma** [comment]
最新版已修复此问题。前往插件市场更新 gocqhttp 插件可以解决。更新方式：

1. 点击「插件市场」，搜索「gocqhttp」
2. **查看最新版本号是否不小于 3.1.1**，如果不是，请点击右上角的刷新按钮，直到再次出现 gocqhttp 插件
3. 选择版本为最新版本，点击对话框右下角的「更新」
4. 刷新界面，等待 Koishi 重新启动
5. 再次按照教程启动 adapter-onebot 插件

**Comment by shigma** [comment]
经反馈和测试，问题应该已经解决。如果还有问题可以继续在此 issue 下回复，我会 reopen。
