### ISSUE TITLE
Bug: qq频道图片无法解析

### ISSUE THREAD

**Issue by Symbol114514** [koishijs/novelai-bot#152]
### Describe the bug

qq频道img2img时无法解析图片

### Steps to reproduce

qq 频道接入 novelai_bot
输入 nai [图片] [prompt]
返回 图片解析失败。

### Expected behavior

请修好它

### Screenshots

![image](https://user-images.githubusercontent.com/109414174/209757378-38ba3d08-de73-45da-bf74-ba5e21acfb32.png)

### Relevant log output

![image](https://user-images.githubusercontent.com/109414174/209757400-15ba3d22-db9d-4343-99d6-a61260bf6761.png)

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: WIndows 10 专业工作站版 22H2
- Adapter: QQguild
- Node version: 18.12.1
- Koishi version: 4.10.10

**Comment by MaikoTan** [comment]
Please provide the platform and corresponding adapter version as well as koishi, otherwise we cannot determine what exactly the problem is.

請提供平臺和相應的介面卡版本以及戀戀，否則我們無法確定到底問題是什麼。

**Comment by Symbol114514** [comment]
BTW
Koishi界面内sd-webui的配置文件有误
依旧使用naifu的配置
![image](https://user-images.githubusercontent.com/109414174/209742095-a7e9ff11-3ac5-4ec5-b788-cc2a6336d40f.png)

**Comment by MaikoTan** [comment]
The configuration issue should be fixed partially in the past.
As for the image extraction issue, did it happen in sandbox either?

配置的問題應該在過去被部分修復。
至於圖像解出問題，它是否也發生在沙箱？
