### ISSUE TITLE
Bug: 启用hiresFix后图片输出错误

### ISSUE THREAD

**Issue by KotoriKoi** [koishijs/novelai-bot#158]
### Describe the bug

本地部署的sd-webui启用hiresFix后图片输出错误，请参考Screenshots中的截图，Koish后台日志一切正常，只有聊天内容不方便展示。通过webui的控制台发现启用hiresFix后输出图像的速度没有太大变换（甚至感觉变快了），这不符合逻辑。

### Steps to reproduce

![参数](https://user-images.githubusercontent.com/91445888/213862791-a4222ea4-95b3-4774-b0c3-6b5ea92f23a1.png)
启用hiresFix后会重现该现象，我不知道其它参数是否有影响，具体参数参考截图，可能的原因是启用hiresFix后超过了图片最大尺寸，但实际测试拉到足够的最大尺寸仍然会重现该现象。

### Expected behavior

无法启用hiresFix会导致图像质量偏低，希望能够给出解决方案。

### Screenshots

![2_SR(PASZ{4ROQ4QW$VV9TH](https://user-images.githubusercontent.com/91445888/213862570-60d252c8-7035-4745-abd5-7a94f126aaa4.png)

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version:

**Comment by MaikoTan** [comment]
Please provide your webui commit SHA here also. I cannot reproduce this issue on my side currently.

請在此處提供您的 webui 提交 SHA。 我目前無法在我側重現此問題。

**Comment by MaikoTan** [comment]
Also, the `hires fix` feature is actually fix the problem that when you are generating large image like more than `1024*1024`, there might be multiple characters or entities that are not what you want. So when you enable the `hires fix` feature, it would firstly generate a smaller image and then use i2i to enlarge it to the requested resolution.
So I don't know that you would get lower quality images without the `hires fix` flag.

See https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#hires-fix

另外，`hires fix` 功能實際上解決了當您生成類似超過 `1024*1024` 的大圖像時，可能會有多個字符或實體不是您想要的問題。 因此，當您啟用 `hires fix` 功能時，它會先生成較小的圖像，然後使用 i2i 將其放大到要求的分辨率。
 所以我不知道如果沒有 `hires fix` 標誌，您會得到質量較低的圖像。

睇 https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#hires-fix

**Comment by MaikoTan** [comment]
Yep, I also found that [this commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/81490780949fffed77493b4bd741e96ec737fe27) changes the behaviour of `hires fix` feature, and after that AUTOMATIC1111 added [another commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/d4fd2418efb0986a8226add0b800fb5c73ffb58c) that allows you to use the old `hires fix` again.
Maybe it causes the problem, but I am not very sure.

**Comment by MaikoTan** [comment]
Also notice here, the `hires fix` feature was changed since the commit that is mentioned above, now the first part would use the `width` and `height` directly from API payloads, and then enlarge it by multiplying a constant (default is 2).

So in the future, we should change type of the `hiresFix` as a number to carry the enlargement multipliers.

還要注意這裡，'hires fix' 特性在上面提到的 commit 後發生了變化，現在第一部分將直接從 API 有效載荷中使用 `width` 和 `height`，然後通過乘以一個常量（默認是 2).

所以在未來，我們應該將 hiresFix 的類型更改為一個數字來攜帶放大倍數。

**Comment by MaikoTan** [comment]
Par exemple, the current behaviour is like:
when you using `nai -r 512x512 -H girl`, you're getting an image in `1024*1024` instead of the original `512*512`.

例如，當前的行為是這樣的：
當您使用 `nai -r 512x512 -H girl` 時，您將獲得 1024*1024 格式的圖像，而不是原始的 512*512 圖像。
