### ISSUE TITLE
onebot 一直显示正在创建 go-cqhttp 子进程

### ISSUE THREAD

**Issue by shigma** [koishijs/novelai-bot#16]
已有多人反馈此问题。此 issue 用于收集情报和追踪问题。

**Comment by shigma** [comment]
https://github.com/koishijs/novelai-bot/issues/3#issuecomment-1272532414

**Comment by shigma** [comment]
来自 dc 用户的反馈：

![image](https://user-images.githubusercontent.com/33423008/194759540-94bba2a4-7581-4a2d-b50b-0c8032d89f5a.png)

**Comment by Nomelande** [comment]
![111](https://user-images.githubusercontent.com/115414202/194765290-d18ec5f9-28ee-42e0-b51c-6adb19c7bdf1.PNG)
沙盒运行novelai正常，onebot应该是完全按照教程进行的，但是点击右上角启动后会弹出空白命令行与提示窗口（如图），确认两次后会自动关闭，控制台卡在“正在创建go-cqhttp子进程”

**Comment by shigma** [comment]
最新版已修复此问题。前往插件市场更新 gocqhttp 插件可以解决。更新方式：

1. 点击「插件市场」，搜索「gocqhttp」
2. **查看最新版本号是否不小于 3.1.1**，如果不是，请点击右上角的刷新按钮，直到再次出现 gocqhttp 插件
3. 选择版本为最新版本，点击对话框右下角的「更新」
4. 刷新界面，等待 Koishi 重新启动
5. 再次按照教程启动 adapter-onebot 插件

**Comment by Nomelande** [comment]
感谢，已成功创建 go-cqhttp 子进程。
![1111](https://user-images.githubusercontent.com/115414202/194769667-ad3f7081-5cee-4931-ab42-20fa1a7ec9d2.PNG)

1.但是测试画画并不会响应，安装echo插件后echo命令也不响应（如图）；
![222](https://user-images.githubusercontent.com/115414202/194769610-4e90e54b-f420-4bc9-b425-80a0346fd16e.PNG)

2.沙盒测试均正常；

3.go-cqhttp命令行仍为空白
![333](https://user-images.githubusercontent.com/115414202/194769648-a112e5f3-7d6a-498a-9ef7-b37f75601f8e.PNG)

怀疑onebot可能仍有问题，但我还不清楚需要提供哪些日志文件。抱歉

**Comment by shigma** [comment]
@Nomelande 我刚刚用最新版试了一下，没有复现你的报错。如果可以的话能提供一下这两个文件吗：

- data\instances\default\koishi.yml
- data\instances\default\accounts\你的QQ号\config.yml

上述 data 目录位于你的解压路径：D:\Software\koishi-desktop-win-x64-v0.6.1

这两个文件内的密码请自行替换成 wwwwww，QQ 号请自行替换成 123456（只替换数字部分，如果有引号请原样保留）。

文件直接上传至此 issue 或使用 pastebin 或加群私发均可。

**Comment by Nomelande** [comment]
你好，已解决


报错原因是我输入的selfid是手机号而并非QQ号，换成QQ号后所有插件均可正常运行。我的问题，抱歉


大佬花费这么多时间回复我的问题，非常感谢！


ps：网络不佳，github上的提问明天再编辑！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月10日(周一) 凌晨1:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [koishijs/novelai-bot] onebot 一直显示正在创建 go-cqhttp 子进程 (Issue #16)




 
@Nomelande 我刚刚用最新版试了一下，没有复现你的报错。如果可以的话能提供一下这两个文件吗：
  
data\instances\default\koishi.yml
 
data\instances\default\accounts\你的QQ号\config.yml
  
上述 data 目录位于你的解压路径：D:\Software\koishi-desktop-win-x64-v0.6.1
 
这两个文件内的密码请自行替换成 wwwwww，QQ 号请自行替换成 123456（只替换数字部分，如果有引号请原样保留）。
 
文件直接上传至此 issue 或使用 pastebin 或加群私发均可。
