### ISSUE TITLE
Bug: bot会将尖括号转成&lt;

### ISSUE THREAD

**Issue by yi03** [koishijs/novelai-bot#161]
### Describe the bug

现在在stable diffusion webui的prompt里直接写使用`<lora:amberGenshinImpact_flexibleV1:1>`就可以调用相应的lora模型
![](https://user-images.githubusercontent.com/32034998/214495048-467e89a5-a3d3-4640-b998-8a62d3323275.png)
但是这样在沙盒或者qq中使用bot时bot会把尖括号转成`&lt;`。
![](https://user-images.githubusercontent.com/32034998/214495092-cac7af2b-e96c-488f-808a-069e22948d97.png)
![](https://user-images.githubusercontent.com/32034998/214495430-73204938-56b5-42f7-8535-e46fed7cffcc.png)
导致webui无法调用相应的lora模型。

我测试使用的lora模型是这个 https://civitai.com/models/4503/amber-genshin-impact-lora

### Steps to reproduce

发送nai 1girl,<lora:amberGenshinImpact_flexibleV1:1>

### Expected behavior

尖括号不被转义

### Launcher

Koishi CLI (koishi start)

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: Windows 11
- Adapter: onebot
- Node version: 18.12.1
- Koishi version: 4.11.3
- koishi-plugin-novelai version: 1.16.0

**Comment by shigma** [comment]
现在 sd 有尖括号的语法吗？

**Comment by MaikoTan** [comment]
> 现在 sd 有尖括号的语法吗？

Yes, there is a new extension called "lora" that requires `<>` to be indicated which was added about several days ago.

**Comment by yi03** [comment]
> 现在 sd 有尖括号的语法吗？

![image](https://user-images.githubusercontent.com/32034998/214505058-e1a57309-ced4-4072-a121-5c0f22a7de8a.png)
最新版sd-webui点击最后的箭头指向的那个图，会在prompt里出现一个尖括号包着的prompt。官方wiki里大概找了找没找到说明，不过确实是有效的。

**Comment by MaikoTan** [comment]
I am not familiar with the transform mechanic in the novelai plugin, so I would like to ask @shigma -chan to do this.
