### ISSUE TITLE
Bug: `sampler` disappeared when switching between `type` with some values

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/novelai-bot#169]
### Describe the bug

![image](https://user-images.githubusercontent.com/19927330/217144058-9fcac479-4ba1-4bb1-9442-8838a648f9d2.png)

**When you set a sampler with `sd-webui` type, and then switch to `login` or `token`.**

![image](https://user-images.githubusercontent.com/19927330/217144142-593a96a8-0fe8-45fc-81c0-26599e2eac54.png)

:tada: **Samplers gone!** :tada:

### Steps to reproduce

1. Set `type` to `sd-webui`, `sampler` to `DPM++2S a`
2. Switch `type` to `login`
3. Sampler gone!

### Expected behavior

Give back `sampler`s!

### Launcher

Koishi CLI (koishi start)

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS:  Ubuntu 20.04
- Adapter:  Any
- Node version:  16.4.1
- Koishi version:  4.11.5

**Comment by MaikoTan** [comment]
And, don't know why but there should be a section header called `参数设置`.

**Comment by shigma** [comment]
已修复（请注意更新到最新版本的 koishi 和 console，两个都要）
