### ISSUE TITLE
反馈下使用过程遇到的问题

### ISSUE THREAD

**Issue by Z-fly** [koishijs/novelai-bot#17]
![image](https://user-images.githubusercontent.com/10470892/194760459-b6007532-ffd1-422a-8417-7c806ba30cc4.png)
这个地方设置成0.0.0.0，这种情况下，open还是在本地打开，所以应该还是要localhost的。
![image](https://user-images.githubusercontent.com/10470892/194760635-4b453bf5-fcbd-4282-a834-a889bca71ede.png)
![image](https://user-images.githubusercontent.com/10470892/194760553-8d6453b6-7080-417e-9aff-7ffc0da4b681.png)

![image](https://user-images.githubusercontent.com/10470892/194760736-eab5604f-9537-45bf-a2b5-b343206310bf.png)
这个点击保存后，应该加个提示保存成功与否，我一开始以为一直都没保存成功。

**Comment by shigma** [comment]
> 这个点击保存后，应该加个提示保存成功与否，我一开始以为一直都没保存成功。

感谢反馈，后续会做。

**Comment by ilharp** [comment]
Koishi Desktop 的 [v0.6.2](https://github.com/koishijs/koishi-desktop/releases/tag/v0.6.2) 已经发版并修复了上述 <https://github.com/koishijs/koishi-desktop/issues/60> 问题。直接使用 msi 安装包或 zip 压缩包覆盖即可修复。

**Comment by shigma** [comment]
> 感谢反馈，后续会做。

没修完就关了，真好啊.jpg 🤣

**Comment by shigma** [comment]
已经修完了，更新 market 插件到 1.4.0 版本即可。
