### ISSUE TITLE
Bug: 在 prompt 处不必要地将 "<" 和 ">" 符号转义成了 "&lt;" 和 "&gt;"

### ISSUE THREAD

**Issue by 255doesnotexist** [koishijs/novelai-bot#177]
### Describe the bug

虽然将 "<" 和 ">" 符号进行转义能有效避免恶意注入攻击，但部分模型训练时也使用了此符号包裹 tag。

如 lora 模型中，普遍性有用 "<" 和 ">" 作为 trigger words 的惯例。

在这样的情况下，传递的 prompt 中会与预期不符地将此符号转义。导致使用了该符号的 prompt 失效。

[关于 Lora 模型](https://zhuanlan.zhihu.com/p/600628691)

### Steps to reproduce

提交任意包含 "<" 或 ">" 符号的 prompt 即可复现。

### Expected behavior

该符号不被转义，以原义形式传递给 webui。

### Screenshots

![_93JJWQ${G%0RWX0{`T 0K4](https://user-images.githubusercontent.com/19223209/220087802-19fcb297-c043-409b-b721-de494598273b.png)

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: Windows Server 2019
- Adapter: QQ
- Node version: v18.12.1
- Koishi version: 4.11.6
- Plugin version: 1.16.4

**Comment by ilharp** [comment]
Duplicate of #161

**Comment by MaikoTan** [comment]
This bug is already fixed and released in the `1.17.0` version.

**Comment by shigma** [comment]
翻译：这个 bug 已经修复了，现在行为正常，只是显示错了。之后会修。

**Comment by shigma** [comment]
已修复，更新到 1.17.1 版本即可。
