### ISSUE TITLE
Bug: novelai plugin translate prompt into lower case makes lora not usable

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/novelai-bot#178]
### Describe the bug

The novelai plugin translate the whole prompt into lower case, but some lora network's name contains upper case letters, then the `sd-webui` backend just reports `lora xxx not found`.

*Also stripped out underline?*

### Steps to reproduce

1. install the koishi novelai plugin 1.17.2
2. type `nai girl, <lora:GenshinImpactHutao_V1:1>`
3. `sd-webui` error: `lora genshinimpacthutao v1 not found`
4. and the returned image was totally no relationship with Hu Tao-chan.

### Expected behavior

Able to use lora properly.

### Launcher

Koishi CLI (koishi start)

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS:  Debian 10 (buster)
- Adapter:  OneBot
- Node version:  16.18.1
- Koishi version:  4.11.6

**Comment by 2364918101** [comment]
解决了吗，我也是这样的

**Comment by shigma** [comment]
修了。
