### ISSUE TITLE
Bug: 添加违禁词后关键词无效

### ISSUE THREAD

**Issue by cqw163** [koishijs/novelai-bot#179]
### Describe the bug

添加违禁词后关键词无效
不管给机器人什么关键词都是随机出图，只留1个违禁词也是一样。全部删除就正常

### Steps to reproduce

-

### Expected behavior

-

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version:

**Comment by MaikoTan** [comment]
What did yout set for the forbidden words? Please provide some reprodusible exemples.

**Comment by cqw163** [comment]
重新去测试了下，是不能添加中文违禁词，添加了就关键词无效。英文违禁词使用正常
