### ISSUE TITLE
Feature: 请求支持Lora

### ISSUE THREAD

**Issue by SurviveZ** [koishijs/novelai-bot#180]
### Scope

Stable Diffusion WebUI (AUTOMATIC1111)

### Describe the problem related to the feature request

Lora可稳定出图元素，但当前插件不支持Lora tag，使作用有了局限性。

### Describe the solution you'd like

支持 <lora:dingzhenlora_v1>这种格式tag使用lora模型

### Describe alternatives you've considered

暂无

**Comment by yi03** [comment]
目前这个插件会转写下划线和大写字母，可以把lora文件重命名，把下划线和大写字母去掉就可以用了。

**Comment by MaikoTan** [comment]
Yep, currently the plugin didn't do a special processing for any extra networks, so LoRas would be treated as normal prompts. It is possible to add a new option for this in the future.

**Comment by SurviveZ** [comment]
> 目前这个插件会转写下划线和大写字母，可以把lora文件重命名，把下划线和大写字母去掉就可以用了。

还是不行

**Comment by yi03** [comment]
> > 目前这个插件会转写下划线和大写字母，可以把lora文件重命名，把下划线和大写字母去掉就可以用了。
> 
> 还是不行

比如可以把lora模型的文件 `dingzhenlora_v1.safetensors` 改名为 `丁真.safetensors` ，然后发送 `<lora:丁真:1>` 就可以用了。

**Comment by SurviveZ** [comment]
> > > 目前这个插件会转写下划线和大写字母，可以把lora文件重命名，把下划线和大写字母去掉就可以用了。
> > 
> > 
> > 还是不行
> 
> 比如可以把lora模型的文件 `dingzhenlora_v1.safetensors` 改名为 `丁真.safetensors` ，然后发送 `<lora:丁真:1>` 就可以用了。

实测仍然无法识别

**Comment by yi03** [comment]
> > > > 目前这个插件会转写下划线和大写字母，可以把lora文件重命名，把下划线和大写字母去掉就可以用了。
> > > 
> > > 
> > > 还是不行
> > 
> > 
> > 比如可以把lora模型的文件 `dingzhenlora_v1.safetensors` 改名为 `丁真.safetensors` ，然后发送 `<lora:丁真:1>` 就可以用了。
> 
> 实测仍然无法识别

你的novelai是最新版吗

**Comment by SurviveZ** [comment]
> > > > > 目前这个插件会转写下划线和大写字母，可以把lora文件重命名，把下划线和大写字母去掉就可以用了。
> > > > 
> > > > 
> > > > 还是不行
> > > 
> > > 
> > > 比如可以把lora模型的文件 `dingzhenlora_v1.safetensors` 改名为 `丁真.safetensors` ，然后发送 `<lora:丁真:1>` 就可以用了。
> > 
> > 
> > 实测仍然无法识别
> 
> 你的novelai是最新版吗

是的，我在webui上可以正常使用lora，但使用koishi的novelai插件它无法识别lora标签

**Comment by yi03** [comment]
> > > > > > 目前这个插件会转写下划线和大写字母，可以把lora文件重命名，把下划线和大写字母去掉就可以用了。
> > > > > 
> > > > > 
> > > > > 还是不行
> > > > 
> > > > 
> > > > 比如可以把lora模型的文件 `dingzhenlora_v1.safetensors` 改名为 `丁真.safetensors` ，然后发送 `<lora:丁真:1>` 就可以用了。
> > > 
> > > 
> > > 实测仍然无法识别
> > 
> > 
> > 你的novelai是最新版吗
> 
> 是的，我在webui上可以正常使用lora，但使用koishi的novelai插件它无法识别lora标签

你的novelai插件是最新版吗

**Comment by SurviveZ** [comment]
> > > > > > > 目前这个插件会转写下划线和大写字母，可以把lora文件重命名，把下划线和大写字母去掉就可以用了。
> > > > > > 
> > > > > > 
> > > > > > 还是不行
> > > > > 
> > > > > 
> > > > > 比如可以把lora模型的文件 `dingzhenlora_v1.safetensors` 改名为 `丁真.safetensors` ，然后发送 `<lora:丁真:1>` 就可以用了。
> > > > 
> > > > 
> > > > 实测仍然无法识别
> > > 
> > > 
> > > 你的novelai是最新版吗
> > 
> > 
> > 是的，我在webui上可以正常使用lora，但使用koishi的novelai插件它无法识别lora标签
> 
> 你的novelai插件是最新版吗

我的koishi显示不兼容novelai 1.17.3，安装后显示未安装插件

**Comment by yi03** [comment]
> > > > > > > > 目前这个插件会转写下划线和大写字母，可以把lora文件重命名，把下划线和大写字母去掉就可以用了。
> > > > > > > 
> > > > > > > 
> > > > > > > 还是不行
> > > > > > 
> > > > > > 
> > > > > > 比如可以把lora模型的文件 `dingzhenlora_v1.safetensors` 改名为 `丁真.safetensors` ，然后发送 `<lora:丁真:1>` 就可以用了。
> > > > > 
> > > > > 
> > > > > 实测仍然无法识别
> > > > 
> > > > 
> > > > 你的novelai是最新版吗
> > > 
> > > 
> > > 是的，我在webui上可以正常使用lora，但使用koishi的novelai插件它无法识别lora标签
> > 
> > 
> > 你的novelai插件是最新版吗
> 
> 我的koishi显示不兼容novelai 1.17.3，安装后显示未安装插件

先在依赖管理里更新koishi到最新版，然后更新novelai插件。

**Comment by SurviveZ** [comment]
> > > > > > > > > 目前这个插件会转写下划线和大写字母，可以把lora文件重命名，把下划线和大写字母去掉就可以用了。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 还是不行
> > > > > > > 
> > > > > > > 
> > > > > > > 比如可以把lora模型的文件 `dingzhenlora_v1.safetensors` 改名为 `丁真.safetensors` ，然后发送 `<lora:丁真:1>` 就可以用了。
> > > > > > 
> > > > > > 
> > > > > > 实测仍然无法识别
> > > > > 
> > > > > 
> > > > > 你的novelai是最新版吗
> > > > 
> > > > 
> > > > 是的，我在webui上可以正常使用lora，但使用koishi的novelai插件它无法识别lora标签
> > > 
> > > 
> > > 你的novelai插件是最新版吗
> > 
> > 
> > 我的koishi显示不兼容novelai 1.17.3，安装后显示未安装插件
> 
> 先在依赖管理里更新koishi到最新版，然后更新novelai插件。

成功了，谢谢老哥

**Comment by shigma** [comment]
fixed by f1179b999bc3ad9e75e6820db6990c22067d755d.
