### ISSUE TITLE
Bug: 发生未知错误，沙盒测试无法通过

### ISSUE THREAD

**Issue by DyeLA** [koishijs/novelai-bot#181]
### Describe the bug

沙盒测试输入nai指令有正确回应help列表，但是加上tag会出现未知错误。

### Steps to reproduce

已更新koishi到最新的4.11.9，novelAI插件版本为1.17.3，沙盒测试输入nai或其他对应指令有回应help列表。
但是加上tag后沙盒测试显示发生未知错误，中间也没有显示正在作画。

### Expected behavior

已经重装novel插件，依然无法解决问题。

### Screenshots

[image](https://user-images.githubusercontent.com/127010181/222947535-3a230d6f-1359-48f5-ae4e-9d8f521dcd30.png)

### Relevant log output

```shell
2023-03-05 15:06:31 [E] novelai TypeError: hash_length cannot be null or undefined
at f (C:\Users\Administrator\AppData\Roaming\Koishi\(Desktop(data\instances (default\node_modules\libsodium-
wrappersldist\modules\libsodium-wrappers.js:1:17851)
at m (Cc:\Users Administrator\AppData \Roaming\Koishi\Desktop\data\instances\default\(node_modules \libsodium-
wrappers \dist\modules\libsodium-wrappers.js:1:17895)
at Xe (C:\Users \Administrator \AppData \Roaming\Koishi\Desktop\data\instances\default\node_modules libsodium-
wrappers \dist\modules\libsodium-wrappers.js :1:49004)
at calcAccessKey
(c:\Users \Administrator \AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules
\koishi-plugin-novelai\lib\utils.js:61: 139)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async login
(C: \Users \Administrator\AppData\Roaming(Koishi\Desktop\data\instances\default\node_modules
koishi-plugin-novelai\lib\utils.js :98:18)
at async _Command.<anonymous>
(C: \Users \Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules
\koishi-plugin-novelai\lib\index.js:172:21)
at async Array.<anonymous>
(C: \Users\Administrator'ApData Roaming Koishi\Desktop\dataNinstances 'default(node modules(koishijs core\lib\index.cjs:1653:14)
```

### Launcher

Koishi Desktop

### Backend

NovelAI (帐号密码)

### Versions

- OS: <-- WindowsServer 2022 -->
- Koishi version:

**Comment by MaikoTan** [comment]
这很奇怪。

我没有一个有效的novelai账户，所以我不能说这里有什么问题。但如果你能为我们提供更多的信息，将会很有帮助。

1. 检索 `envinfo` 并发布在这里

  这很简单，只要打开你的 `小石控制台`，然后点击右下方的状态栏，`envinfo`信息就会自动复制到你的剪贴板上。

2. 打开终端，然后获得更多信息

  首先，你应该[打开小石的终端](https://forum.koishi.xyz/t/topic/303/3)。然后输入`yarn why libsodium-wrappers`(或者`yarn list --pattern 'libsodium-wrappers'`如果`yarn why`不起作用)，然后把输出复制到这里。

3. 登录NovelAI，然后检查你的订阅是否已过期

  进入[novelai.net](https://novelai.net/)，登录后检查你的订阅。

通过www.DeepL.com/Translator（免费版）翻译

<details><summary>The original text</summary>

This is weird.

I don't have a valid novelai account, so I cannot tell what is wrong here. But it would be helpful if you could provide more information for us.

1. Retrieve the `envinfo` and post here

  This is simple, just open your "Koishi Console" and then click the status bar at the bottom right, the `envinfo` information would be automatically copied into your clipboard.

2. Open terminal and then get more information

  First, you should [open the terminal to Koishi](https://forum.koishi.xyz/t/topic/303/3). then type `yarn why libsodium-wrappers` (or `yarn list --pattern 'libsodium-wrappers'` if `yarn why` not work), then copy the output here.

3. Login to NovelAI and then check if your subscription was expired

  Go to [novelai.net](https://novelai.net/), login and then check your subscription.

</details>

**Comment by acgnmoe** [comment]
我也这个问题

**Comment by acgnmoe** [comment]
2023-03-20 12:00:16 [E] novelai TypeError: hash_length cannot be null or undefined
                            at f (/koishi/node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js:1:17851)
                            at m (/koishi/node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js:1:17895)
                            at Xe (/koishi/node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js:1:49004)
                            at calcAccessKey (/koishi/node_modules/koishi-plugin-novelai/lib/utils.js:61:139)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async login (/koishi/node_modules/koishi-plugin-novelai/lib/utils.js:98:18)
                            at async _Command.<anonymous> (/koishi/node_modules/koishi-plugin-novelai/lib/index.js:172:21)
                            at async Array.<anonymous> (/koishi/node_modules/@koishijs/core/lib/index.cjs:1660:14)

**Comment by shigma** [comment]
这个得看下你们的配置项了，type 用的哪个？

**Comment by DyeLA** [comment]
> 这个得看下你们的配置项了，type 用的哪个？

使用账号密码登录和授权令牌登录，均为此错误信息。

**Comment by MaikoTan** [comment]
看起来像是来自`libsodium-wrapper`的错误，我们的常量`crypto_pwhash_SALTBYTES`在这里使用

https://github.com/koishijs/novelai-bot/blob/d9e345df9f9b1e2ccc88d1af359a9c51ea6cb2ca/src/utils.ts#L69

是在0.7.9版本后未被定义。

我用下面的代码进行了测试，它在0.7.8版本时输出`16`，但在0.7.9、0.7.10和0.7.11版本时`未定义`。

```js
const libsodium = require('libsodium-wrappers')

;(async () => {
  await libsodium.ready
  console.log(libsodium.crypto_pwhash_SALTBYTES)
})()
```

另一方面，`sumo`版本（`libsodium-wrappers-sumo`）在每个版本都运行良好，也许我们可以改用`sumo`版本，它是用[Emscripten](https://github.com/kripken/emscripten)编译的WASM。

通过www.DeepL.com/Translator（免费版）翻译

<details>
<summary>Click to expand original text</summary>

It looks like the bug from `libsodium-wrapper`, the constant `crypto_pwhash_SALTBYTES` we are using here

https://github.com/koishijs/novelai-bot/blob/d9e345df9f9b1e2ccc88d1af359a9c51ea6cb2ca/src/utils.ts#L69

is undefined after version 0.7.9.

I tested with the code below, it outputs `16` at version 0.7.8, but `undefined` at version 0.7.9, 0.7.10 and 0.7.11.

```js
const libsodium = require('libsodium-wrappers')

;(async () => {
  await libsodium.ready
  console.log(libsodium.crypto_pwhash_SALTBYTES)
})()
```

On the other hand, the `sumo` version (`libsodium-wrappers-sumo`) works well at every version, maybe we could switch to the `sumo` version instead, which is WASM compiled with [Emscripten](https://github.com/kripken/emscripten).

</details>

**Comment by TeoZler** [comment]
出现同样的错误。请问目前这个bug是否有临时的解决方案？
