### ISSUE TITLE
Feature: 希望可以增加自动保存功能

### ISSUE THREAD

**Issue by onlytheworld** [koishijs/novelai-bot#182]
### Scope

NovelAI, NAIFU, Stable Diffusion WebUI (AUTOMATIC1111), Stable Horde, Others

### Describe the problem related to the feature request

希望可以自动保存所有请求和所有生成图片，以方便日后查验

### Describe the solution you'd like

如上

**Comment by MaikoTan** [comment]
I think this feature is beyond the functions of this plugin, it would be better to create a new plugin for the auto-save feature. Besides, `SD-WebUI` could auto-save images generated via API in their settings, you may consider that one as well.
