### ISSUE TITLE
Bug: 关于配置页面sd的api地址404

### ISSUE THREAD

**Issue by ShanShuWu** [koishijs/novelai-bot#191]
### Describe the bug

配置页面输入的格式为https://xxx.xxxx.xxx:端口/，浏览器可以通过该地址使用webui，但是向机器人发出绘图请求会返回404，请问api地址为什么样子最合适？

### Steps to reproduce

配置页面输入的格式为https://xxx.xxxx.xxx:端口/，浏览器可以通过该地址使用webui，但是向机器人发出绘图请求会返回404

### Expected behavior

输入api地址，请求绘图，返回图片

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version:

**Comment by MaikoTan** [comment]
it looks like you didn't [pass `--api` as the argument to sd-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API), please check.

**Comment by MaikoTan** [comment]
By the way, it is hardly get information from your title, please also clarify it.

**Comment by ShanShuWu** [comment]
好像确实是--api在最近一次更换地址时出了问题，正在检查，感谢
