### ISSUE TITLE
AxiosError: Request failed with status code 502

### ISSUE THREAD

**Issue by jiajiangtao122** [koishijs/novelai-bot#192]
### Describe the bug

在qq群发 画图  关键词  的时候报这个错误 看到sd-webui后台接受到请求了 也在画 但是不返回 就爆这个错误 刚开始就报

### Steps to reproduce

发画图 关键词就会报错

### Expected behavior

希望不爆错能正常返回

### Screenshots

![UKJ$BT6U ~N}90F01M)8834](https://user-images.githubusercontent.com/48207940/229403019-a481c957-6873-4650-b106-09861dc866df.png)
![EGEFQ9{8Q8} LKEI4IUXX0U](https://user-images.githubusercontent.com/48207940/229403037-73d6b66b-9bfa-4684-80f0-0b9b504b0d8c.png)

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version:

**Comment by MaikoTan** [comment]
Is this issue still reproducible now?
