### ISSUE TITLE
Feature: NovelAI recently upgraded the whole backend, this plugin cannot get the image now

### ISSUE THREAD

**Issue by JackyNKL** [koishijs/novelai-bot#193]
### Scope

NovelAI

### Describe the problem related to the feature request

Recently, this plugin start sending some broken images. I just checked the NovelAI website and find out they now transfer zip file instead of images. 

### Describe the solution you'd like

I don't know if we can ask the server to send images instead of zip files to the plugin. Also, please add some new samplers that NovelAI is now supported.

### Describe alternatives you've considered

Maybe just unzip the image locally...

**Comment by MaikoTan** [comment]
fixed in #213
