### ISSUE TITLE
Feature(SD-WebUI): Specify Hires Steps for Hires Fix Feature in command options

### ISSUE THREAD

**Issue by chqw163** [koishijs/novelai-bot#194]
### Scope

NovelAI

### Describe the problem related to the feature request

hires fix的Hires steps能不能加个数值选项，现在是和steps一样的，要跑几十步，但模型推荐5-10步就够了，不需要那么多。或者有没有大佬能给个改代码的方法啊- -    现在不用难受，用了太慢

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

**Comment by MaikoTan** [comment]
這是個好的提議，將會實現在 v1.18.0 或更晚，因爲有一個大改動對於 NovelAI 外掛程式在之前，當前沒有時間去做。

**Comment by Ninzore** [comment]
想弄了
