### ISSUE TITLE
Bug: novelai TypeError: hash_length cannot be null or undefined

### ISSUE THREAD

**Issue by lin-strive** [koishijs/novelai-bot#196]
### Describe the bug

在沙盒中测试报错
![image](https://user-images.githubusercontent.com/94910081/235054995-9e482b5e-c978-4779-88a3-59b8552acf98.png)
![image](https://user-images.githubusercontent.com/94910081/235055024-7423e7af-1724-4203-afdf-a90f9140ffbb.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/94910081/235055132-f22aaf36-a0e2-41fa-a34e-88e84a5b4d50.png)

### Expected behavior

能正常使用该插件

### Launcher

Koishi Desktop

### Backend

NovelAI (帐号密码)

### Versions

System:
    OS: Linux 5.4 Alpine Linux
    CPU: (2) x64 AMD EPYC 7K62 48-Core Processor

Binaries:
    Node: 18.15.0
    Yarn: 1.22.19

Koishi:
    Core: 4.12.6
    Console: 5.6.2

koishi-plugin-novelai | 1.17.4 (最新)

**Comment by MaikoTan** [comment]
duplicate with #181 and may be fixed by #195
