### ISSUE TITLE
Feature: 当使用-i参数时一次性请求指定的所有图片

### ISSUE THREAD

**Issue by t4wefan** [koishijs/novelai-bot#198]
### Scope

Stable Diffusion WebUI (AUTOMATIC1111)

### Describe the problem related to the feature request

当使用-i参数时，默认会在一次请求完成之后再请求下一次，若在其中有其他人（通过非插件的方式）请求画图，队列会被延迟（插队）。或者使用负载均衡时，请求不会同时发到多个节点计算，拖慢了响应时间

### Describe the solution you'd like

当使用-i参数时一次性向后端发送指定次数的请求
这样可以避免插队，也可以避免负载均衡在这里失效

### Describe alternatives you've considered

暂无

### Additional context

差不多了

**Comment by MaikoTan** [comment]
Added a `-b` option for batch sampling rather than changing the current behaviour of `-i`
