### ISSUE TITLE
telegram无法使用img2img功能

### ISSUE THREAD

**Issue by Gelmezon** [koishijs/novelai-bot#20]
![微信图片_20221010093203](https://user-images.githubusercontent.com/20065068/194789067-85b9e3e4-a996-4a89-bd61-c7d49c443bc2.jpg)
![微信图片_20221010093211](https://user-images.githubusercontent.com/20065068/194789071-5b0d04b1-2ac4-46c0-88ec-42f3ef6fb926.jpg)

**Comment by shigma** [comment]
@Gelmezon 更新了 3.4.6，麻烦再试试 🤣
