### ISSUE TITLE
Bug: upscaler 不生效

### ISSUE THREAD

**Issue by pzzmyc** [koishijs/novelai-bot#207]
### Describe the bug
我是本地运行的sd web ui
不管选择哪个，效果都一样，
我是如何发现的：
当选择ldsr超分器的时候，图片直接顺溜跑完20步，然后超分20步
然而当我回到sdwebui的时候，再次使用这个ldsr超分器，他居然当场开始下载模型，意思是之前压根没有使用超分模型，
使用其他超分器也一样，没有调用，（下载的模型中断了损坏了，他照样能跑完，但是webui里就会报错
![image](https://github.com/koishijs/novelai-bot/assets/43562427/bbf955f7-2c3c-4ef5-9c3c-f2d0488df41e)

### Steps to reproduce

/

### Expected behavior

/

### Screenshots

/

### Relevant log output

```shell
/
```

### Launcher

Koishi Desktop

### Backend

NovelAI (帐号密码)

### Versions

![image](https://github.com/koishijs/novelai-bot/assets/43562427/5f9df5ed-14f8-48d6-83b7-c74afaf7f8f3)

**Comment by Neptune1990** [comment]
这个选项似乎只对
![image](https://github.com/koishijs/novelai-bot/assets/107494041/470acaad-0976-4180-afaa-f8a28c2f6bdd)
起效。
高清修复的放大算法可能默认是Latent之类的吧，设置重绘强度设置0.4左右就是一团糊。

**Comment by pzzmyc** [comment]
确实，我没想到他可能只对图生图生效，但是有没有可能让文生图也能使用超分器

**Comment by MaikoTan** [comment]
Yes, the upscaler is originally used for image-to-image only, we can make it available for hires either.

**Comment by Neptune1990** [comment]
其实挺需求可以自选高清修复自选模型和重绘幅度的
