### ISSUE TITLE
增强图片发生未知错误

### ISSUE THREAD

**Issue by TZFC** [koishijs/novelai-bot#21]
复现方法：
输入：
增强 + 图片
反回：
在画了在画了
发生未知错误。

已确认开启允许anlas
已确认有足够的anlas
已确认 约稿 tag 指令正常

log:
```
[38;5;8m2022-10-10 18:39:15[0m [D] [38;5;32;1mgocqhttp[0m 收到群 GUILD 内 USER 的消息: 增强 [CQ:image,file=3e2648db65a062028503d1b78776f949.image,subType=1,url=URL] (-1293613710)
[38;5;8m2022-10-10 18:39:16[0m [D] [38;5;32;1mgocqhttp[0m 发送群 GUILD 的消息: [{"type":" ... (-975030812)
[38;5;8m2022-10-10 18:39:16[0m [D] [38;5;32;1mgocqhttp[0m 收到群 GUILD 内 MYSELF 的消息: 在画了在画了 (-975030812)
[38;5;8m2022-10-10 18:39:18[0m [D] [38;5;32;1mgocqhttp[0m 收到群 GUILD 内 MYSELF 的消息: 发生未知错误。 (1558930526)
[38;5;8m2022-10-10 18:39:18[0m [D] [38;5;32;1mgocqhttp[0m 发送群 GUILD 的消息: [{"type":" ... (1558930526)
```

**Comment by shigma** [comment]
应该还有发生错误时的错误日志，如果有的话请发一下。

**Comment by TZFC** [comment]
前面截的来自于
C:\Users\Administrator\Downloads\koishi-desktop-win-x64-v0.6.1\data\instances\default\logs
在C:\Users\Administrator\Downloads\koishi-desktop-win-x64-v0.6.1\data\instances\default\accounts\1582679599\logs下没有这段时间的log，说明没有warning或以上的报错
另：
在novelai.net上看anlas并没有被扣除

**Comment by shigma** [comment]
此问题稳定出现吗？多试几次总是有此问题吗？

**Comment by TZFC** [comment]
没有成功过。尝试了重启各个插件，重启koishi，都不行。

**Comment by TZFC** [comment]
在discord测试也是遇到相同问题

**Comment by shigma** [comment]
请问传入的图片是过去生成的吗？还是其他来源的图？

**Comment by TZFC** [comment]
是用户随指令一同上传的图。大小是小于限制的，在novelai.net网页端可以顺利上传。可以从log中看到QQ给了这个图片一个url。

**Comment by shigma** [comment]
来个图片给我测试一下。

**Comment by shigma** [comment]
刚刚测试的结果是，如果把 text2img 返回的图片进行增强是没问题的。自己拍一张增强会报错。

**Comment by TZFC** [comment]
是的！我刚刚也是两种都试了下。把 text2img 返回的图片进行增强确实没问题。自己上传的（已经压缩到800KB）不行

**Comment by shigma** [comment]
问一下具体数据：图片的宽、高、magnitude。

**Comment by shigma** [comment]
有可能是要求 upscale 后的体积不超过 1M，也有可能是要求宽高必须是 8 的倍数之类……

**Comment by TZFC** [comment]
测试了
1.宽682高677 - 错误
2.宽1024高1024 - 错误
3.768高512 （生成的） -可以

**Comment by shigma** [comment]
有设置缩放比例吗

**Comment by TZFC** [comment]
没有，就是简单的 增强 tag1,tag2 +图片

**Comment by shigma** [comment]
试试先 txt2img 个非标准尺寸的（比如 768x768）再增强，然后自己做一张 768x512 也试试增强

**Comment by TZFC** [comment]
1. 在网页端txt2img生成了768x768的图片，保存到本地
2. 在本地另存一个resize到768*512的
3. 分别增强
![Screenshot 2022-10-11 002647](https://user-images.githubusercontent.com/51830440/194997195-bd0437f4-91f2-4fba-b479-e2a0445048cd.png)

**Comment by TZFC** [comment]
测试用图：
![Generated768_768](https://user-images.githubusercontent.com/51830440/194997376-0893a727-736b-4cba-813c-d058bf188908.png)

![Resized768_512](https://user-images.githubusercontent.com/51830440/194997402-e20ecd44-7f6c-4afa-ae74-07a9e9c41b9d.png)

**Comment by Ninzore** [comment]
经过测试，似乎在长宽和 < 1280，也就是640x640以下时可以放大1.5倍；而在 < 1024，也就是512x512以下时可以放大2倍。有着长宽和在大于1280后不能进行upscale，以及长宽和不能超过2048的限制。

**Comment by TZFC** [comment]
如果不需要放大，只是想根据 上传的图+tag 生成新图， 可以是默认大小的话指令是什么样的呢？类似于 upscale=1 的参数有吗？

**Comment by Ninzore** [comment]
> 如果不需要放大，只是想根据 上传的图+tag 生成新图， 可以是默认大小的话指令是什么样的呢？类似于 upscale=1 的参数有吗？
有的
新的doc已经pr上来了但是还没合并，先看这里吧 https://github.com/koishijs/novelai-bot/pull/23/commits/18eb8cdefae0ca1b962f765ca2b1b889fb62ad30

**Comment by TZFC** [comment]
太好了！感谢！
