### ISSUE TITLE
Bug: 以图画图不可用

### ISSUE THREAD

**Issue by lingyunytc** [koishijs/novelai-bot#214]
### Describe the bug

通过回复图片使用画图指令，QQ内携带图片使用画图指令，机器人均回复输入中含有无效内容

### Steps to reproduce

携带图片使用画图指令

### Expected behavior

正确的使用图像进行画图

### Screenshots

![2222](https://github.com/koishijs/novelai-bot/assets/61460076/2d76545a-1c6a-4d85-a1cb-edcb526d19c0)

### Launcher

Koishi Desktop

### Backend

NovelAI (Token)

### Versions

- OS: Windows 10 
- Adapter: QQ
- Node version: 
- Koishi version:

**Comment by MaikoTan** [comment]
Which version are you using?
Will it reproduce in sandbox as well?

**Comment by lingyunytc** [comment]
> Which version are you using?您使用哪个版本？ Will it reproduce in sandbox as well? 它也会在沙箱中重现吗？

novelai插件使用的1.20.0
这个问题在沙盒内也同样存在
![image](https://github.com/koishijs/novelai-bot/assets/61460076/11dcc891-9540-450a-bede-dfdf8bce7358)

**Comment by MaikoTan** [comment]
Oh I think you have accidentally disabled the `image` feature in the config.

**Comment by lingyunytc** [comment]
> Oh I think you have accidentally disabled the `image` feature in the config.哦，我认为您不小心禁用了配置中的 `image` 功能。

嗯....它们似乎是正确的
![image](https://github.com/koishijs/novelai-bot/assets/61460076/e92e3d04-4fbe-4180-8fea-1fc452f27959)

**Comment by MaikoTan** [comment]
Okay, I will take a look soon.

**Comment by lingyunytc** [comment]
> Okay, I will take a look soon.好的，我很快就看一下。

我发现当是否允许使用点数，这个处于关闭状态时不会再回复输入中含有无效内容，但以图画图的图片和原图基本不相干，即便使用-N 0.2

**Comment by MaikoTan** [comment]
Is it still an issue nowadays? I didn't reproduce it locally.
