### ISSUE TITLE
Feature: 在参数一致的情况下，机器人生成的图片质量远远低于web端生成的图片。

### ISSUE THREAD

**Issue by PJ1059** [koishijs/novelai-bot#218]
### Describe the problem related to the feature request

在参数一致的情况下，机器人生成的图片质量远远低于web端生成的图片。
![image](https://github.com/koishijs/novelai-bot/assets/154049356/8bf49c48-baaa-4119-9d01-470cc09ad590)
这是在机器人上生成的图片

![image](https://github.com/koishijs/novelai-bot/assets/154049356/fa266b4f-0e85-4983-9ad3-a98610f762cb)
这是在web端生成的图片

我最近才使用的novelai，我没有在web端中找到Scale这项设置，倒是只见到这两类似的东西
![image](https://github.com/koishijs/novelai-bot/assets/154049356/7e778446-50fe-4eee-8249-938e933016bd)
![image](https://github.com/koishijs/novelai-bot/assets/154049356/fdbbd6c2-285d-4e00-a707-5b2a1d599cd4)

### Describe the solution you'd like

![{924783DE-5F91-4ac7-9DD8-AD37CE7D855F}](https://github.com/koishijs/novelai-bot/assets/154049356/0e4f688d-a9dd-423e-9a62-411d06e1b16b)
希望更新新的采样接口

**Comment by spqdem** [comment]
一样的问题

**Comment by KlNon** [comment]
同样的问题
