### ISSUE TITLE
Bug: 默认分辨率配置项消失

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/novelai-bot#226]
### Describe the bug

插件配置中的 resolution 选项消失，dev 环境下正常

感觉上是 schemastery 的问题，可能不需要在此修改代码

### Steps to reproduce

```
yarn clone koishijs/novelai-bot
yarn dev // 此时可以在插件配置中看到 resolution 选项
yarn build
yarn start // resolution 消失了
```

### Expected behavior

prod 与 dev 行为一致
或
resolution 选项正确显示

### Screenshots

dev
![image](https://github.com/koishijs/novelai-bot/assets/37006258/e12675d6-74e1-4932-a8cf-4496a8489f88)
prod
![image](https://github.com/koishijs/novelai-bot/assets/37006258/c5b07e57-7573-4fa4-9637-708008c0c85b)

### Launcher

Koishi CLI (koishi start)

### Backend

NovelAI (帐号密码)

### Versions

- OS: Windows 10
- Adapter: sandbox
- Node version: 20.11.0
- Koishi version: 4.16.8

**Comment by MirrorCY** [comment]
忽略截图中其余部分的不同，不是一个环境

**Comment by Fubuki171** [comment]
期待修复

**Comment by MaikoTan** [comment]
Upstream bug related to https://github.com/koishijs/koishi/issues/1382
