### ISSUE TITLE
Bug: novelai无法使用，不知道什么情况

### ISSUE THREAD

**Issue by Coisini-H** [koishijs/novelai-bot#238]
### Describe the bug

![QQ截图20240302200950](https://github.com/koishijs/novelai-bot/assets/52484657/0765e0ed-c567-41af-83d6-ad72e11b191f)

安装好开启加速器都不行，api都是刚刚获取的，加速器是开的全局

### Steps to reproduce

安装就有，其他功能正常

### Expected behavior

希望可以解决这个问题，就是无法使用nai3挺麻烦的

### Screenshots

![QQ截图20240302200950](https://github.com/koishijs/novelai-bot/assets/52484657/1249ca7a-739e-4fe9-b3d5-d41c5e7a0098)

### Launcher

Koishi Desktop

### Backend

NovelAI (Token)

### Versions

- OS: 
- Adapter: 
- Node version: 
- Koishi version:

**Comment by MirrorCY** [comment]
尝试全局配置的代理项输入 `socks://127.0.0.1:port`

**Comment by Coisini-H** [comment]
> 尝试全局配置的代理项输入`socks://ip:port`

大佬我使用的是clash，不太懂在哪里输入

**Comment by MirrorCY** [comment]
如果你没有改动 Clash 的默认配置，尝试输入 socks://127.0.0.1:7890

> 不太懂在哪里输入

![image](https://github.com/koishijs/novelai-bot/assets/37006258/55aca7f4-f953-416f-9cc3-385a25c2de59)

**Comment by Coisini-H** [comment]
![QQ截图20240302203654](https://github.com/koishijs/novelai-bot/assets/52484657/3d19768d-4a07-4d51-9b2d-329ef75ae538)
![QQ截图20240302203804](https://github.com/koishijs/novelai-bot/assets/52484657/e76f93e7-0a38-4254-b147-c7a1047af2ea)
![QQ截图20240302203832](https://github.com/koishijs/novelai-bot/assets/52484657/33e31da1-6dc6-48e0-bb40-154fb5822afe)


> 如果你没有改动 Clash 的默认配置，尝试输入 socks://127.0.0.1:7890
> 
> > 不太懂在哪里输入
> 
> ![图像](https://private-user-images.githubusercontent.com/37006258/309472832-55aca7f4-f953-416f-9cc3-385a25c2de59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzODI1ODYsIm5iZiI6MTcwOTM4MjI4NiwicGF0aCI6Ii8zNzAwNjI1OC8zMDk0NzI4MzItNTVhY2E3ZjQtZjk1My00MTZmLTljYzMtMzg1YTI1YzJkZTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDEyMjQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjOTU1NjQ5NTY2MWM5OGYzZGZlOTNhNGZlOWYzNzM3NDY1YWZhZDgxMzhhMTYwMTk5NzVkZjdiYjFmM2RhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.79Ng1FcUp0IldOMoOExSnmmqu4y9dNlUDN5ZrQqNi6A)

之前是直接错误，现在有提示了，不知道什么问题

**Comment by MirrorCY** [comment]
#236

**Comment by Coisini-H** [comment]
> #236 等待更新

好吧

**Comment by MirrorCY** [comment]
@Coisini-H 定位了，发版前你可以自己 clone 下来改改
![image](https://github.com/koishijs/novelai-bot/assets/37006258/dbe5346e-a8a9-47e6-9676-baf5cea47270)

**Comment by MirrorCY** [comment]
已发版，等待插件市场更新

**Comment by MaikoTan** [comment]
Fixed by #239 , Please install the latest version

**Comment by Coisini-H** [comment]
@MirrorCY @MaikoTan 行，谢谢大佬们，我等他更新
