### ISSUE TITLE
Feature: 支持使用novelai官方的apikey

### ISSUE THREAD

**Issue by assassinliujie** [koishijs/novelai-bot#243]
### Scope

NovelAI

### Describe the problem related to the feature request

novelai自己有官方的apikey，用token不知道为什么没法画

### Describe the solution you'd like

-

**Comment by Coisini-H** [comment]
因为官方改了api，他们没改，我手动修改或者使用反向代理的都无法使用

官方以前API：https://api.novelai.net
官方现在API：https://image.novelai.net

以前的api改成查询账户信息api了
新的才是跑图的

**Comment by dorioku** [comment]
需要将
```
.....
const res = await ctx.http.axios((0, koishi_1.trimSlash)(config.endpoint) + path,{
.....
```
中的"config.endpoint"替换成'https://image.novelai.net/'
或者在config中的endpoint附近增加新值

**Comment by MaikoTan** [comment]
Will do in next patch. Thanks for investigating.

**Comment by Yangthemob** [comment]
换言之，现在的koishi-novelai插件，是没有办法正常使用novelai官方api登录、画图的吗？
我尝试了账号密码登录和token登录，也尝试了将endpoint从https://api.novelai.net改为https://image.novelai.net/，都没有成功。
我没有查阅到关于这些情况的教程，希望能得到指导。

**Comment by Yangthemob** [comment]
根据个人尝试，当前可以通过先在设置为https://api.novelai.net/ 的情况下启用插件访问一次完成登录，然后重载为https://image.novelai.net/ ，后续的请求就可以正常绘图了。
希望之后的版本能做好对新endpoint的适配，不需要我这样的歪门邪道来维持使用hhhh

**Comment by dorioku** [comment]
> 根据个人尝试，当前可以通过先在设置为https://api.novelai.net/ 的情况下启用插件访问一次完成登录，然后重载为https://image.novelai.net/ ，后续的请求就可以正常绘图了。 希望之后的版本能做好对新endpoint的适配，不需要我这样的歪门邪道来维持使用hhhh

你可以在config.js的
```
endpoint: koishi_1.Schema.string().description('API 服务器地址。').default('https://api.novelai.net'),
```
后面添加一句
```
endpoint2: koishi_1.Schema.string().description('画图 服务器地址。').default('https://image.novelai.net'),
```
![image](https://github.com/koishijs/novelai-bot/assets/49861289/8fd9252f-858a-4e83-9839-8f9414e0fe50)

然后在config.d.ts中的
```
endpoint?: string;
```
后面新增
```
endpoint2?: string;
```
![image](https://github.com/koishijs/novelai-bot/assets/49861289/a221942f-83b0-45c7-b351-3bf76f620084)

最后将index.js中的
```
const res = await ctx.http.axios((0, koishi_1.trimSlash)(config.endpoint) + path,{
```
改成
```
const res = await ctx.http.axios((0, koishi_1.trimSlash)(config.endpoint2) + path, {
```
![image](https://github.com/koishijs/novelai-bot/assets/49861289/3b1a8193-c95c-45c7-a79d-88d95dd30934)

这样你能在后台直接编辑地址了
![image](https://github.com/koishijs/novelai-bot/assets/49861289/7b16e9ef-650e-4600-b9e4-7de8728af67e)
"**endpoint2**" 可以根据需求改成不同的id
