### ISSUE TITLE
Bug: 秋叶包 sd-webui 环境下绘图不定时出现 404 错误

### ISSUE THREAD

**Issue by Alirea10** [koishijs/novelai-bot#245]
### Describe the bug

使用koishi+novelAI插件，配合秋叶包使用（详细参数见下）。会偶发出现404异常。（其他插件不会）

### Steps to reproduce

1.双清koishi desktop，
2.全部插件更新至最新版（2024年5月3日）
3.安装novelAI插件，
4.配置登录方式为sd-webui，endpoint为 http://localhost:7860/ 
5.保存配置，在沙盒中使用nai fox指令
发生未知错误（404）

### Expected behavior

其应当正常输出图片。

### Screenshots

》Alirea：nai fox
》koishi：少女绘画中
》koishi：发生未知错误（404）

### Relevant log output

```shell
日志不存在额外输出

p.j
plugins:
  proxy-agent:q7a0po: {}
  group:server:
    server:7vkklu:
      port: 5140
      maxPort: 5149
    ~server-satori:12hj79: {}
    ~server-temp:djr0mt: {}
  group:basic:
    admin:qxhxif: {}
    ~bind:rwogdz: {}
    commands:38of1e: {}
    help:dyo2wk: {}
    ~inspect:7s9yxv: {}
    locales:h0yj0j: {}
    rate-limit:umxii5: {}
    telemetry:3qmuce: {}
  group:console:
    actions:euc4zm: {}
    analytics:1xakzk: {}
    android:7b2jlt:
      $if: env.KOISHI_AGENT?.includes('Android')
    ~auth:x0ugqi: {}
    config:1yh6s9: {}
    console:jr0yt8:
      open: true
    dataview:sbnrq1: {}
    desktop:dm4rvb:
      $if: env.KOISHI_AGENT?.includes('Desktop')
    explorer:7z1iov: {}
    logger:28e96o: {}
    insight:yonwcx: {}
    market:nyeu9z:
      search:
        endpoint: https://registry.koishi.t4wefan.pub/index.json
    notifier:mby6i9: {}
    oobe:06iskp: {}
    sandbox:220k3q: {}
    status:jwjj3b: {}
    theme-vanilla:7cno78: {}
  group:storage:
    database-sqlite:qe2x5u:
      path: data/koishi.db
    ~database-mysql:hd7zhu:
      database: koishi
    ~database-mongo:98orsu:
      database: koishi
    assets-local:du9azj: {}
  group:adapter:
    ~adapter-dingtalk:cjpe5z: {}
    ~adapter-discord:v7njnn: {}
    ~adapter-kook:eavg6j: {}
    ~adapter-lark:0e7bpg: {}
    ~adapter-line:jl6mz0: {}
    ~adapter-mail:tq7a0k: {}
    ~adapter-matrix:5uja18: {}
    ~adapter-qq:1h7m62: {}
    ~adapter-satori:0bjhan: {}
    ~adapter-slack:5904b2: {}
    ~adapter-telegram:ho53qj: {}
    ~adapter-wechat-official:39n8tt: {}
    ~adapter-wecom:hzokyb: {}
    ~adapter-whatsapp:pxbu8i: {}
    ~adapter-zulip:tvgn1r: {}
    adapter-onebot:7jg6un:
      selfId: '[删除]'
  novelai:65d5ai:
    type: sd-webui
    endpoint: http://127.0.0.1:7860/
    negativePrompt: >-
      lowres, {bad}, error, fewer, extra, missing, worst quality, jpeg
      artifacts, bad quality, watermark, unfinished, displeasing, chromatic
      aberration, signature, extra digits, artistic error, username, scan,
      [abstract]
    output: minimal
    textSteps: 20
    scale: 7
    imageSteps: 20
    maxSteps: 30
    sampler: k_dpmpp_3m_sde_ka
    upscaler: R-ESRGAN AnimeVideo
  group:develop:
    $if: env.NODE_ENV === 'development'
    hmr:jalbom:
      root: .
  sd-taylor:urlm7y:
    api_path: http://127.0.0.1:7860/
    resolution: 1024x1024
    negative_prompt: >-
      lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit,
      fewer digits, cropped, worst quality, low quality, normal quality, jpeg
      artifacts, signature, watermark, username, blurry
    cfg_scale: 7
```

### Launcher

Koishi Desktop

### Backend

Stable Diffusion WebUI (AUTOMATIC1111)

### Versions

- OS: Windows 11
- Adapter: sendbox onebot
- Node version: 20.12.1
- Koishi version: v4.17.5
- 绘世（SDwebui整合包/秋叶包）v2.8.4 build 327

-novelai: 1.22.2
-sd-taylor: 1.3.0
均为当日（2024年5月3日16:23:42）最新

System:
    OS: Windows 11 10.0.22621
    CPU: (6) x64 AMD Ryzen 5 3500X 6-Core Processor             

Binaries:
    Node: 20.12.1
    Yarn: 4.0.1

Koishi:
    Core: 4.17.5
    Console: 5.28.4
    Koishi Desktop: 1.1.1

### Additional context

尝试过的问题检验：
使用相似的koishi插件 sd-taylor，开启后在 api_path 中 写入 http://127.0.0.1:7860/ 启用插件
在沙盒中使用 tl fox 正常出图，且测试过同时开启novelai插件与sd-taylor，或只开启其一，结果一致
》Alirea：nai fox
》koishi：少女绘画中
》koishi：发生未知错误（404）
》Alirea：tl fox
》koishi：已经在努力画了喵
》koishi：[图片]

尝试检查本地代理，开启关闭均无法使用。

检查整合包，已确认开启api，在本地部署。

尝试重启koishi desktop 问题照常。

之前不知道怎么回事，在没关机的情况下他突然就不404正常出图了几次，然后怎么都无法复现。

也许和nai依赖的http服务有关？

**Comment by MaikoTan** [comment]
> 在没关机的情况下

???
What??

**Comment by MaikoTan** [comment]
Cannot reproduce with sd-webui latest commit (https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0).

**Comment by Alirea10** [comment]
将绘世中的SD内核版本改为2023年第50周-1.7.0版本（）可以正常使用了，可能还真是 SD的问题

**Comment by MaikoTan** [comment]
Still not very sure if it is exactly the upstream bug, you could keep this issue open, see if there are similar ones.
