### ISSUE TITLE
Feature: 不知道会有novelai官方的采样器吗？

### ISSUE THREAD

**Issue by KlNon** [koishijs/novelai-bot#252]
### Scope

NovelAI

### Describe the problem related to the feature request

![image](https://github.com/koishijs/novelai-bot/assets/58141387/540d86c5-03f6-4caa-9b94-7afac104bc05)
好像只有默认的采样器。

### Describe the solution you'd like

![image](https://github.com/koishijs/novelai-bot/assets/58141387/84d9de91-a86b-4190-9926-58023cd0be46)
新增官方的这些采样器
另外看起来似乎在[#221](https://github.com/koishijs/novelai-bot/pull/221)中修复,但为什么采样器仍然只有默认的呢？

**Comment by Neptune1990** [comment]
还有就是启用SMEA&DYN支持
