### ISSUE TITLE
Bug: novelai图生图不可用

### ISSUE THREAD

**Issue by RealityError** [koishijs/novelai-bot#256]
### Describe the bug

novelai图生图提示错误
![image](https://github.com/user-attachments/assets/d7ffd866-ccba-48f4-9693-8684a156182d)
按照如下教程操作后仍提示400
![image](https://github.com/user-attachments/assets/b81faf8f-0686-4519-ae58-2f88b476a9cc)

### Steps to reproduce

使用插件通过novelai进行img2ing操作

### Expected behavior

正常图生图

### Launcher

Containers (Docker, Kubernates, etc)

### Backend

NovelAI (Token)

### Versions

- OS: ubunutu 22.04
- Adapter: onebot 
- Koishi version:  4.17.1

**Comment by MaikoTan** [comment]
> Thanks for the issue, but there are some details should you clarify:
> 
> - Does it still happen on the version `1.24.0`?
> - Does the `400` error happen on the Text-to-Image feature (i.e prompt without an image)
> - Would you happen to have a log about the issue?

感谢您提出问题，但有一些细节需要您澄清：

- 在 `1.24.0` 版本中问题是否仍然存在？
- `400` 错误是否发生在文本转图片功能上（即没有图像的提示）？
- 您是否有关于此问题的日志？

**Comment by Neptune1990** [comment]
打开了“是否允许使用点数”选项了吗，我的话没开会400，开了可以图生图，但是似乎没有起效。

**Comment by Neptune1990** [comment]
我在未开启“是否允许使用点数。”的时候也会发生未知错误 (400)。

**Comment by MirrorCY** [comment]
最新版本复现
