### ISSUE TITLE
Feature: 希望可以调整默认尺寸

### ISSUE THREAD

**Issue by Midrash0052** [koishijs/novelai-bot#266]
### Scope

NovelAI

### Describe the problem related to the feature request

现在还只能用novel的默认小图尺寸（512*768），每次用其他尺寸要多输入个-r的命令，希望可以增加调整默认尺寸的功能

### Describe the solution you'd like

在插件界面就能修改默认生成的尺寸

**Comment by MirrorCY** [comment]
有这个配置项的，如果找不到就是上游 bug
https://github.com/koishijs/novelai-bot/blob/main/src/config.ts#L402-L410
https://github.com/koishijs/koishi/issues/1382

**Comment by Midrash0052** [comment]
> 有这个配置项的，如果找不到就是上游 bug https://github.com/koishijs/novelai-bot/blob/main/src/config.ts#L402-L410 [koishijs/koishi#1382](https://github.com/koishijs/koishi/issues/1382)

ok，谢谢解答
