### ISSUE TITLE
使用telegram 调用novelai-bot的img2img功能时 axios会报请求失败

### ISSUE THREAD

**Issue by Gelmezon** [koishijs/novelai-bot#29]
![微信图片_20221012140429](https://user-images.githubusercontent.com/20065068/195262684-8a47fced-0043-46bb-a035-52c9f61a0bc4.jpg)

使用telegram 调用novelai-bot的img2img功能时 axios会报请求失败

**Comment by shigma** [comment]
感谢反馈。问题已经定位，我们将尽快修复。
