### ISSUE TITLE
发生未知错误。

### ISSUE THREAD

**Issue by cherry0804** [koishijs/novelai-bot#3]
![image](https://user-images.githubusercontent.com/72689056/194586382-6e371d54-2c0b-41e7-8dcc-ab6acf62bf03.png)
哪裡可以查看問題?

**Comment by shigma** [comment]
刚刚修复了无法在沙盒中使用的问题，你需要更新一下版本到 1.3.3。

**Comment by cherry0804** [comment]
还是不行，一样发生未知错误。
我去查看日志出现这样子
![image](https://user-images.githubusercontent.com/72689056/194589604-31ed290f-3011-4c94-9afd-08266b340155.png)

**Comment by shigma** [comment]
使用此功能需要付费 (或者公车)。已更新 [快速搭建](https://github.com/koishijs/koishi-plugin-novelai#%E5%BF%AB%E9%80%9F%E6%90%AD%E5%BB%BA) 教程。

**Comment by toppac** [comment]
novelai Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
环境：沙盒

**Comment by shigma** [comment]
> novelai Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) 环境：沙盒

是国内环境吗？服务器能访问公网吗？

**Comment by toppac** [comment]
> 

Desktop版本的，如何配置代理？request.proxyAgent 貌似不起作用。。

**Comment by shigma** [comment]
> Desktop版本的，如何配置代理？request.proxyAgent 貌似不起作用。。

你是怎么配置的？

**Comment by toppac** [comment]
> > 桌面的如何配置代理？代理的其他版本。
> 
> 你是怎么配置的？

现在可以了，全局设置的报错，我改成了使用进程代理整个koishi,
并且不使用koishi的gocqhttp，外挂了了一个。
(内置的无法正常工作，onebot一直显示正在创建 go-cqhttp 子进程）

**Comment by shigma** [comment]
我另开一个 issue 吧，这个已经 off topic 了。
