### ISSUE TITLE
图片解析失败

### ISSUE THREAD

**Issue by Edwardsaga** [koishijs/novelai-bot#32]
是需要配置代理服务器地址吗？
一般是根据什么配置？

**Comment by shigma** [comment]
请提供足够的信息：

- 插件版本
- 使用的适配器及其版本
- 解析失败的图片

**Comment by Edwardsaga** [comment]
novelai - 1.7.0
本地naifu端口
![image](https://user-images.githubusercontent.com/37936041/195513516-8be4abb2-eab5-4508-b591-ea044581e361.png)

外挂gocqhttp
正向websocket
config：
  - ws:
      # 正向WS服务器监听地址
      host: 127.0.0.1
      port: 6700
koish：
plugins:
  adapter-onebot:
    protocol: ws
    endpoint: ws://127.0.0.1:6700

关键字功能可以使用，附图时会失败
![image](https://user-images.githubusercontent.com/37936041/195513873-9a1a5251-d57e-4e0d-8157-f3ce7e50f0e0.png)
![image](https://user-images.githubusercontent.com/37936041/195513892-0cea1d2a-fc15-4656-a6f0-39ab82f93db3.png)
使用图片
![V12 @%VW)5HI1N6Y}YO1H_N](https://user-images.githubusercontent.com/37936041/195513920-91283c0c-c22a-48f3-8620-c1e5fe2ed26b.jpg)

**Comment by shigma** [comment]
情况了解了。我这边测试一下。

**Comment by shigma** [comment]
感谢您的反馈。问题已修复，请更新至 1.7.1 版本。
