### ISSUE TITLE
img2img在naifu上的使用问题

### ISSUE THREAD

**Issue by xuebiya** [koishijs/novelai-bot#34]
如果我要使用naifu，并且要用到img2img，打开了allowAnlas，可是naifu不是官方的，这样就导致用不了的情况，只能使用text2img

**Comment by shigma** [comment]
具体用不了是指？

**Comment by xuebiya** [comment]
> 

提示请求失败 请求超时

**Comment by shigma** [comment]
超时应该就是单纯的超时吧…？服务器是本地的吗？

**Comment by xuebiya** [comment]
Colab上的

**Comment by shigma** [comment]
如果访问很慢的话试试调高 requestTimeout，以及全局设置中配置 proxyAgent（默认情况是不认系统代理的）。

**Comment by xuebiya** [comment]
设置了proxyAgent，text2img正常使用，img2img提示图片解析失败

**Comment by shigma** [comment]
刚刚不是说超时的吗 :rofl:
解析失败一般有报错日志，发出来看看。

**Comment by xuebiya** [comment]
刚刚是没有设置proxyAgent，看了一下日志，把requestTimeout调高了 可以正常使用了，谢谢！！

**Comment by xuebiya** [comment]
还有一个问题，img2img的强度是用什么参数

**Comment by shigma** [comment]
strength 吗？`--strength` 或者 `-N`。

**Comment by xuebiya** [comment]
好的 谢谢

**Comment by shigma** [comment]
吐槽：s 开头的词太多已经分不过来了……

scale, size, step, strength, sampler, seed, ...
