### ISSUE TITLE
需要undesired Contents参数

### ISSUE THREAD

**Issue by borraken** [koishijs/novelai-bot#40]
RT，这个用的还蛮多的
默认的超时时间建议设高一些，这算一个小坑
另外API 服务器地址可能是在哪里写死了，我无法通过直接修改来变更，需要手动把代码批量替换掉

**Comment by shigma** [comment]
&gt; 需要undesired Contents参数
支持 sd-webui 语法，可以通过 negative prompts: 后接 undesired。

&gt; 默认的超时时间建议设高一些
了解了，我会改成 1 分钟，感谢您的建议。

&gt; 另外API 服务器地址可能是在哪里写死了
配置项 endpoint。

**Comment by borraken** [comment]
是的，endpoint 设置不起作用
这个问题是在我尝试使用ai.nya.la的API替换时出现的

**Comment by shigma** [comment]
> 是的，endpoint 设置不起作用
> 这个问题是在我尝试使用ai.nya.la的API替换时出现的

我确认了一下源码，目前修改配置保存后不会应用 endpoint。我会尽快修复，感谢反馈！

**Comment by shigma** [comment]
请注意：ai.nya.la 的 API 应是 `https://api.nya.la`。

**Comment by shigma** [comment]
新增了一個 headers 配置項，你可以試試加上 referer 以後看看。

**Comment by shigma** [comment]
Closed due to staleness.
