### ISSUE TITLE
私服怎么搭建？

### ISSUE THREAD

**Issue by batvbs** [koishijs/novelai-bot#41]
To expose an API endpoint of your app in these API docs, set the api_name parameter of the event listener. For more information, see the "API Page" [section](https://gradio.app/sharing_your_app/#api-page) in the guides. To hide this API page, set show_api=False in the Blocks.launch() method.

See the "view api" link in footer of the app above? This is a page that documents the REST API that users can use to query the function. apps can also generate an API page, though the API has to be explicitly named for each event listener, such asInterfaceBlocks
btn.click(add, [num1, num2], output, api_name="addition")
This will document the endpoint to the automatically generated API page. /api/addition/
很明显api需要自己设置，可我不清楚参数啊~

**Comment by MXDexRazero** [comment]
在网上下载naifu的一键包，启动完成后会有个IP，一般是0.0.0.0:6969换成127.0.0.1:6969填写到你的插件里就行，示例截图：
![image](https://user-images.githubusercontent.com/112014237/195872636-09db4358-6b3b-4fba-b685-7d49ab6fba20.png)

**Comment by MXDexRazero** [comment]
> 在网上下载naifu的一键包，启动完成后会有个IP，一般是0.0.0.0:6969换成127.0.0.1:6969填写到你的插件里就行，示例截图： ![image](https://user-images.githubusercontent.com/112014237/195872636-09db4358-6b3b-4fba-b685-7d49ab6fba20.png)

如果ai是放在外部服务器的，那就写外部服务器的IP地址

**Comment by batvbs** [comment]
> > 在网上下载naifu的一键包，启动完成后会有个IP，一般是0.0.0.0:6969换成127.0.0.1:6969填写到你的插件里就行，示例截图：
> 
> 如果ai是放在外部服务器的，那就写外部服务器的IP地址

不支持webui吗？

**Comment by MaikoTan** [comment]
Propose to close this PR and trace webui API support in #59 .

建议关闭此 PR 并在 #59 中跟踪 webui API 支持。

**Comment by shigma** [comment]
确实可以关闭了，不过官网目前还需要一篇 naifu 搭建指南，你愿意来写吗？@MaikoTan

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
