### ISSUE TITLE
在kook里不能使用img2img功能

### ISSUE THREAD

**Issue by MXDexRazero** [koishijs/novelai-bot#42]
我把图片做成表情放在聊天栏，显示"只接受英文输入。"，不做成表情直接放上去又放不上，它会直接把图片先越过文字发出去，先把图片发出去，然后回复图片吧，干脆就没反应不识别了。
![image](https://user-images.githubusercontent.com/112014237/195865418-e0a59047-99f0-4948-aee2-88a3cd5e2833.png)
![image](https://user-images.githubusercontent.com/112014237/195865266-13a6ac99-6669-44b2-b2ea-c862533d198e.png)
![image](https://user-images.githubusercontent.com/112014237/195865754-7db8f86b-5623-4a45-87d4-44355be4c1cc.png)

**Comment by shigma** [comment]
感谢反馈。确实有这个问题，会在 Koishi 下个版本修复。

**Comment by MXDexRazero** [comment]
> 感谢反馈。确实有这个问题，会在 Koishi 下个版本修复。

感谢 希望koishi越来越好

**Comment by shigma** [comment]
刚刚发布的最新版本已经支持了相关功能，欢迎尝试。如有问题可以继续反馈。
