### ISSUE TITLE
Feature Request返回数据的合理化

### ISSUE THREAD

**Issue by HuanLinMaster** [koishijs/novelai-bot#43]
我个人认为可以把以下三句话合并成一个消息发出去
![image](https://user-images.githubusercontent.com/94176676/195969229-a9b3ac26-ed56-43b9-94a1-68ccd65f48c1.png)

优点：
防风控
防刷屏
卡片化

**Comment by shigma** [comment]
你说的很对。目前分三条是因为 QQ 的合并转发，之后会有对其他平台更友好的方案，预计在 Koishi 496 版本实装。

**Comment by HuanLinMaster** [comment]
感谢 希望koishi越来越好

**Comment by shigma** [comment]
现在已经支持 tg、dc 平台合并到一条消息发送了。

**Comment by shigma** [comment]
sandbox 也已合并到一条发送，问题可以视为解决。
