### ISSUE TITLE
Feature Request: 自动撤回 prompt

### ISSUE THREAD

**Issue by H4M5TER** [koishijs/novelai-bot#44]
出于避免刷屏的目的，既然机器人的输出中会带有 prompt，可以在输出图片时撤回用户的输入
我注意到很多用户都自觉地在机器人收到之后手动的撤回

**Comment by shigma** [comment]
机器人在大部分场合下都不是管理员，无权撤回用户的输入。并且大批量的撤回可能会触发风控。

**Comment by Seidko** [comment]
或者换一种思路，机器人不输出prompt，只输出seed等参数，并用回复的方式来显示prompt

**Comment by MaikoTan** [comment]
事实上应该只有 OneBot 会遇到这个问题（以及需要撤回？）
在别的平台上几乎都有 Slash Command 或类似的功能，这种方式不会回显用户的输入。

**Comment by shigma** [comment]
回显的意义其实是方便直接转发，以及修正语法，补全 basePrompt 等等。

**Comment by shigma** [comment]
现在增加了不输出 prompt 的配置项：https://bot.novelai.dev/config.html#output
