### ISSUE TITLE
图片解析失败

### ISSUE THREAD

**Issue by edwer1** [koishijs/novelai-bot#46]
好多图片都解析失败，可能是分辨率问题吗，小的图片倒是可以以图生图，版本1.8.6

**Comment by shigma** [comment]
感谢反馈！
1. 说明你使用的平台
2. 提供一些失败的示例图片（才不是想看色图呢）
3. 请确认一下失败是否稳定（将失败的图再次尝试是否仍然失败）

**Comment by edwer1** [comment]
![image](https://user-images.githubusercontent.com/44490405/195983355-2bbc78db-4023-46c5-b287-1bdaf49760ce.png)
![image](https://user-images.githubusercontent.com/44490405/195983364-48612d09-d412-4916-a9d5-72bdac9fb448.png)
![image](https://user-images.githubusercontent.com/44490405/195983375-81a64676-b499-49d4-87a6-d939901210d9.png)
![image](https://user-images.githubusercontent.com/44490405/195983391-58c96f32-b8e6-46b8-81f7-246ebf095601.png)
![image](https://user-images.githubusercontent.com/44490405/195983406-4daca72c-07de-403c-b121-6b8ca1e71fea.png)

**Comment by edwer1** [comment]
就有些图片怎么都不好使，有些图片就没有这个问题，还有就是发送转发的聊天记录的话，手机总是打不开
![Screenshot_2022-10-15-19-13-24-260_com tencent mo](https://user-images.githubusercontent.com/44490405/195983499-83192d6b-b2f6-4867-b181-6c21802f338a.jpg)
![`FZ5L5S)52~IDC%5_Q6H0FX](https://user-images.githubusercontent.com/44490405/195983515-48077755-f2c1-4df2-a0fd-3a7e3862b9ab.png)

**Comment by shigma** [comment]
请把原始文件上传到这个 issue 中（拖动图片进输入框即可）。

**Comment by edwer1** [comment]
服务器是win2012的

**Comment by edwer1** [comment]
我发的不是原始文件嘛（）

**Comment by H4M5TER** [comment]
你发的是截图

**Comment by edwer1** [comment]
要截图的原始文件啊

**Comment by edwer1** [comment]
![195983355-2bbc78db-4023-46c5-b287-1bdaf49760ce](https://user-images.githubusercontent.com/44490405/195983663-b2dc0166-03e2-4656-8f28-5b3efa363bca.png)

**Comment by edwer1** [comment]
![195983364-48612d09-d412-4916-a9d5-72bdac9fb448](https://user-images.githubusercontent.com/44490405/195983668-7fbc50d0-91af-4aa3-b4ff-9482162b2688.png)

**Comment by shigma** [comment]
这个问题请给 qq 提 issue（嗯

**Comment by edwer1** [comment]
![195983375-81a64676-b499-49d4-87a6-d939901210d9](https://user-images.githubusercontent.com/44490405/195983671-99b00f91-e75c-46aa-9ad7-8c08ee4bc46d.png)

**Comment by edwer1** [comment]
![195983391-58c96f32-b8e6-46b8-81f7-246ebf095601](https://user-images.githubusercontent.com/44490405/195983681-dfb78465-b5bc-4b6c-9f2a-d49e1bb7e2fb.png)

**Comment by edwer1** [comment]
![195983406-4daca72c-07de-403c-b121-6b8ca1e71fea](https://user-images.githubusercontent.com/44490405/195983685-3189b66c-d6fb-4c5a-9c3d-c914014eeeda.png)

**Comment by edwer1** [comment]
![195983499-83192d6b-b2f6-4867-b181-6c21802f338a](https://user-images.githubusercontent.com/44490405/195983697-63f35e4a-535a-4646-b048-f6cf70d3d2b9.jpg)

**Comment by edwer1** [comment]
![195983515-48077755-f2c1-4df2-a0fd-3a7e3862b9ab](https://user-images.githubusercontent.com/44490405/195983702-12c3b68c-5e73-44d1-ad7e-b9f8d22b6f04.png)

**Comment by edwer1** [comment]
确实是qq的问题但是能不能不用转发聊天记录（）

**Comment by NWYLZW** [comment]
什么 ntr ，居然还有真寻 bot

**Comment by edwer1** [comment]
是的（）挂了两个反向ws

**Comment by ilharp** [comment]
Koishi 夺舍真寻，总觉得很 NTR 啊（

**Comment by edwer1** [comment]
确实是夺舍（）

**Comment by lingyunytc** [comment]
![1](https://user-images.githubusercontent.com/61460076/195984043-1c6a0b84-3a5b-4f10-9354-c05f0fd71bb7.png)

**Comment by MaikoTan** [comment]
> 确实是qq的问题但是能不能不用转发聊天记录（）

I think that would be worth to have a new option to the plugin switching transform message forward or not. But can you mention it in a new issue?
我认为对于是否转发插件切换转换消息有一个新选项是值得的。 但是你能在一个新的问题上提到它吗？

**Comment by lingyunytc** [comment]
这个图片会失败，重试多次也一样

**Comment by HuanLinMaster** [comment]
哥们看看日志？

**Comment by edwer1** [comment]
行，等一下

**Comment by HuanLinMaster** [comment]
能发一下你的issue链接么 我q群回复的 看不到上下文

**Comment by edwer1** [comment]
https://github.com/koishijs/novelai-bot/issues/46

**Comment by edwer1** [comment]
怪事了，他又好使了

**Comment by edwer1** [comment]
我找找之前的

**Comment by edwer1** [comment]
![MHJ_%`FEL(G28I3M)Q3OXUE](https://user-images.githubusercontent.com/44490405/195984379-b81e371e-a23a-4960-b5fa-6779bcac260b.png)

**Comment by MaikoTan** [comment]
It might be an issue of qq client that you cannot open the merged message group, sometimes relaunch the qq client app would fix it, sometimes not.
可能是qq客户端的问题，无法打开合并的消息组，有时重新启动qq客户端应用程序会修复它，有时不会。

**Comment by MicroCBer** [comment]
考虑抓包看下对合并转发的请求有没有报错啥的

**Comment by MaikoTan** [comment]
Can I ask which service type are you using? The official NovelAI API? Or the leaked NAIFU?
请问您使用的是哪种服务类型？ 官方 NovelAI API？ 还是泄露的奈福？

**Comment by edwer1** [comment]
官方的

**Comment by shigma** [comment]
能重新发送一下「导致失败的原图」而不是聊天记录吗？并且请同时发送一份解析失败同时输出的日志。上面发的可能并不是相关联的日志。

**Comment by shigma** [comment]
问题已定位：`String.fromCharCode()` 直接使用会导致内存越界。将尽快修复。

**Comment by shigma** [comment]
1.9.8 版本已修复此问题。
