### ISSUE TITLE
图片上传失败: image type error: application/octet-stream

### ISSUE THREAD

**Issue by gt4404gb** [koishijs/novelai-bot#47]
15号发现qq经常不返回图片
<img width="347" alt="image" src="https://user-images.githubusercontent.com/28683708/195985019-6e6910e1-7ebd-4691-83ad-085cd5b755b3.png">
看日志是提示图片上传失败: image type error: application/octet-stream
<img width="711" alt="image" src="https://user-images.githubusercontent.com/28683708/195984975-f81000e2-435f-4f23-88d0-a20e64dab769.png">
是否是图片解析方面需要更新？

**Comment by MicroCBer** [comment]
这图片不会解析的吗

**Comment by gt4404gb** [comment]
补充：用的novelai官方的api，另外TG机器人中也有类似的问题，只返回seed和prompt，但是没有图片

**Comment by shigma** [comment]
此问题是由于 novelai 官方服务器就压根没有返回图片导致的。返回的是空白数据。

**Comment by shigma** [comment]
请更新到 1.9.1 版本，该版本尝试加入了空白数据的判断。

**Comment by gt4404gb** [comment]
更新1.9.5后问题解决~另外novelai官方API改成了https://backend-production-svc.novelai.net ,直接更新上去版本的话需要手动更新下地址
