### ISSUE TITLE
发生未知错误 (401)。

### ISSUE THREAD

**Issue by TZFC** [koishijs/novelai-bot#48]
更新至 koishi 4.9.5 和 koishi-plugin-novelai 1.9.5 后，在 koishi 沙盒中测试：
Carol
约稿 plane
Koishi
在画了在画了
Koishi
发生未知错误 (401)。
配置中新增的 headers 项都使用的默认值

**Comment by shigma** [comment]
请确认一下 type 是否设置为 token。

将 type 切换成 login 后重载，再次切换成 token 后重载，看看是否仍有问题。

**Comment by f9207000** [comment]
我現在送出都報展503...
Koishi
在画了在画了
Koishi
发生未知错误 (503)。

**Comment by shigma** [comment]
503 是因为 novelai 更新了后端 API，请将 endpoint 配置项的 api 修改为 backend-production-svc，亲测可解决此问题。

**Comment by shigma** [comment]
Closed due to staleness.
