### ISSUE TITLE
Feature Request：使用回复的方式展示生成的图片

### ISSUE THREAD

**Issue by WhenMelancholy** [koishijs/novelai-bot#50]
![image](https://user-images.githubusercontent.com/21274779/196017620-a406ee3a-3027-4a2e-a336-c8d4dc2d86fb.png)

如题，现在的 one bot 可以在 qq 群中实现如上的效果吗，就是不提供种子和参数，同时直接将生成的图片作为画图指令的回复。这样的话不用点进转发消息也可以看到图片了，而且也知道图片对应的 prompts 是哪些，消息数量也不会很多。

**Comment by shigma** [comment]
可以，我会加一个配置项的。
