### ISSUE TITLE
Feature Request: 失败时自动重试 以及支持添加Undesired Content参数

### ISSUE THREAD

**Issue by Darkatse** [koishijs/novelai-bot#51]
最近NovelAI服务器有点爆炸，感觉可以添加一个maxRetryCount（感觉可以默认为3），重试次数不超过该值时自动重试

还有就是能否支持添加Undesired Content参数（也就是negative prompt），有些想画的图必须添加一些添加Undesired Content参数才能画出来

**Comment by shigma** [comment]
```
约稿 word1 word2 word3
negative prompt: word1 word2 word3
```

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by shigma** [comment]
感谢反馈，最新版 (1.10.1) 已经实现此功能。
