### ISSUE TITLE
onebot连接部署好了，只能发送一次生成图片就挂了

### ISSUE THREAD

**Issue by AshxStudio** [koishijs/novelai-bot#57]
onebot连接部署好了，只能发送一次生成图片就挂了
log里看不出错误 koshi卡住只能手动重启
koshi手动重启后可以发送一次又卡住
以下为重启前全部log 
![image](https://user-images.githubusercontent.com/66589946/196099772-4d9bf688-d771-45c5-ac79-5964d0ef091b.png)

**Comment by AshxStudio** [comment]
![image](https://user-images.githubusercontent.com/66589946/196099998-2f2a5a0d-ed8d-41ba-985d-0507bc7fef29.png)

**Comment by shigma** [comment]
额，怎么关掉了，是你自己配置错误了吗
