### ISSUE TITLE
关于稳定的扩散网页用户界面应用程序接口 / About stable diffusion webui API

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/novelai-bot#64]
## Summary

Currently, the stable diffusion WebUI (abbr. sd-webui) API is still in progress, you can track it at https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/765

To use this feature, you should make sure the `stable diffusion webui` that you're using is the one from `AUTOMATIC1111` and updated to the latest commit.

**If you are not sure what and which version you are using, please follow [this guide](https://github.com/AUTOMATIC1111/stable-diffusion-webui#automatic-installation-on-windows) to fetch a new one!**

You could run sd-webui with `--api` parameter to enable the API routes:

- [How to add command arguments?](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings#webui-user)
- [How to confirm the API routes are running well?](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API)

Then, in your koishi console, switch to `Plugin Configuration` -> `novelai`, down to `Login Settings`, set `type` to `sd-webui`, then write your IP address with port of the machine running sd-webui to `endpoint` field. (e.g. `127.0.0.1:7860` or `192.168.1.100:7860`, etc)

![image](https://user-images.githubusercontent.com/19927330/197379479-4ae612a4-8ae2-40c7-ba1a-0f3a95cb7282.png)

## Progress

- [x] txt2img
- [x] img2img

## Bugs

You can report bugs or issues here in the comments.

------

## 概括

目前稳定的扩散网页用户界面（简称 sd-webui）应用程序接口仍在进行中，您可以在 https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/765 进行跟踪

要使用这个功能，你需要确保你的 `稳定的扩散网页用户界面` 是来自于 `自动1111` 的，并且已更新到最新的提交。

**如果你不确定你在运行的是什么版本，请跟随[这个指南](https://github.com/AUTOMATIC1111/stable-diffusion-webui#automatic-installation-on-windows)获取一个新的!**

你可以用`--api`参数运行sd-webui，以启用应用程序接口路由：

- [如何添加命令行参数？](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings#webui-user)
- [如何确认应用程序接口路由正在运行很好？](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API)

然后，在你的恋石控制台，切换到 "插件配置"->"novelai"，向下到 "登录设置"，将 "类型" 设置为 "sd-webui"，然后将你运行sd-webui的机器的IP地址和端口写到 "终结点" 字段。（例如：`127.0.0.1:7860` 或者 `192.168.1.100:7860` 等）

![image](https://user-images.githubusercontent.com/19927330/197379479-4ae612a4-8ae2-40c7-ba1a-0f3a95cb7282.png)

## 进步
- [x] txt2img
- [x] img2img

## 错误

你可以在这里的评论中报告错误和问题。

**Comment by MaikoTan** [comment]
## txt2img

sd-webui uses different parameters, the big consideration part is sampler.
You see, samplers in novelai.net are just `k_euler_ancestral`, `k_euler`, `k_lms`, `plms` and `ddim`. But there are more and different names of samplers in sd-webui.
See: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/7f8ab1ee8f304031b3404e25761dd0f4c7be7df8/modules/sd_samplers.py#L18-L42

### Consideration

So here we can choose to just "translate" the novelai's sampler name to sd-webui's, or just use different options for sd-webui individually. Depending on approach, it might be a bit painful to do the such fixing.

------

## txt2img

sd-webui使用不同的参数，最大的考虑部分是采样器。
你看，novelai.net中的采样器只有`k_euler_ancestral`、`k_euler`、`k_lms`、`plms`和`ddim`。但是在sd-webui中，有更多不同的采样器名称。
参见：https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/7f8ab1ee8f304031b3404e25761dd0f4c7be7df8/modules/sd_samplers.py#L18-L42

### 考虑因素

所以在这里，我们可以选择只把novelai的采样器名称 "翻译 "成sd-webui的，或者只对sd-webui单独使用不同选项。根据不同的方法，做这样的修正可能会有点痛苦。

**Comment by MaikoTan** [comment]
## img2img

Currently not implemented. Waiting patiently.

------

## img2img

目前没有实施。耐心等待。

**Comment by Seidko** [comment]
最新慢报：img2img api已于此 [commit](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a7c213d0f5ebb10722629b8490a5863f9ce6c4fa) 实现，sd webui 的 img2img的支持可以实验性跟进了。

**Comment by MaikoTan** [comment]
Kusa, why is it so fast?

Je vais jeter un coup d'oeil demain. Merci beaucoup !

草，怎么这么快？

我明天看看。 非常感谢您 ！

**Comment by MaikoTan** [comment]
`Extra`, I mean, the upscale feature was implemented in https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/3511 , but whether to support this in this plugin or not was still in consideration.

`额外`，我的意思是，升级功能在 https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/3511 ，但是否在这个插件中支持这个功能仍然是有争议的。

**Comment by MaikoTan** [comment]
Besides, someone mentioned the `face restoration` and `highres fix` feature in txt2img should be supported. ([discord discussion](https://discord.com/channels/811975252883800125/835780836427038732/1035467833636818954))
I personally think that these features could be supported, but since we have a plugin that is pretty complex for now. I would rather refactor it, split them into a new plugin, and then do such work.

另一方面，有人提出了txt2img中的`面部恢复`和`highres修复`功能应该支持。([不和谐的讨论](https://discord.com/channels/811975252883800125/835780836427038732/1035467833636818954))
我个人认为这些功能可以支持，但是自从我们有了一个目前来讲非常繁杂的插件。我更愿意重构它，分解它们到一个新插件，然后做这个工作。

**Comment by MirrorCY** [comment]
waiting for an upscale feature 🚀

催更！！（不是

**Comment by MaikoTan** [comment]
As the base support for sd-webui was completed, I am going to close this issue, and we can track new features in a new one. Let's bravo to hard-working Maiko aka myself!
