### ISSUE TITLE
控制台basePrompt功能的输入貌似没法识别换行 因此没法识别negative prompt

### ISSUE THREAD

**Issue by DAIORANGE** [koishijs/novelai-bot#66]
官方的示例:
```
约稿 girl
negative prompt: loli
```
示例里negative prompt前面有个回车 
![image](https://user-images.githubusercontent.com/28801505/197128259-b5d96fc0-781c-44bf-8a2f-5ff217770d30.png)

但显示机器人收到的prompt里`negative prompt: loli`没出现

在官方结果对比 negative prompt大概生效了只是没显示
![image](https://user-images.githubusercontent.com/28801505/197130324-422a46e7-c6f4-4f1f-a3ee-f6939b6fa36b.png)
![image](https://user-images.githubusercontent.com/28801505/197130425-27922cb8-c5d9-439a-9d8f-4f6fbc3df773.png)

在basePrompt的输入栏输入自定义的一些tag后
```
masterpiece,best quality,ultra-detailed, illustration,disheveled hair
negative prompt: longbody, lowres, bad anatomy, bad hands, missing fingers, pubic hair,extra digit, fewer digits, cropped, worst quality, low quality
```
![image](https://user-images.githubusercontent.com/28801505/197130805-b929e482-2c5d-42a0-8418-5fdf5e7fdcbc.png)
结果里出现了`negative prompt: `和后续内容 大概意味着negative prompt没被正确识别
又试了下往basePrompt里的内容加`\n`  或者 `\`
```
masterpiece,best quality,ultra-detailed, illustration,disheveled hair
\n negative prompt: longbody, lowres, bad anatomy, bad hands, missing fingers, pubic hair,extra digit, fewer digits, cropped, worst quality, low quality
```
![image](https://user-images.githubusercontent.com/28801505/197131470-653af333-436f-4be6-a635-c328bc28db5a.png)
好像还是不行

basePrompt清空的情况下输入同样的内容
```
约稿 hatsune_miku, masterpiece,best quality,ultra-detailed, illustration,disheveled hair
negative prompt: longbody, lowres, bad anatomy, bad hands, missing fingers, pubic hair,extra digit, fewer digits, cropped, worst quality, low quality
```
![image](https://user-images.githubusercontent.com/28801505/197132147-d675694c-d16c-4a4e-849f-bb52ed0202e7.png)

错误原因可能是因为basePrompt的输入栏只有一行 没法识别换行? 
又或者跟另一个issue里的问题一样 tag太多的情况下除了会卡死以外还会有别的问题?
![image](https://user-images.githubusercontent.com/28801505/197131617-fffe3613-d1ba-4ad9-8055-cb2973c00740.png)

也在basePrompt里试了-u, 也没有用

**Comment by MaikoTan** [comment]
I think a better solution is to add a new option like "baseNegativePrompt" which would be append to the negative prompt in the input. Rather than configuring this `basePrompt` with `negative prompt: blahblah`...

我认为一个更好的解决方案是添加一个新的选项，如 "baseNegativePrompt"，它将被附加到输入中的负面提示。而不是将这个 `basePrompt` 配置为 `negative prompt: blahblah`...

**Comment by MaikoTan** [comment]
Just an FYI, in the code, we "extract" the `negative prompt` part out before adding the `basePrompt` onto it, so you cannot add negative prompt to this option to achieve what you thought. Sorry about that, can you re-word your post if I guessing it right?

仅供参考，在代码中，我们在添加 `basePrompt` 之前将 `negative prompt` 部分 "提取 "出来，所以你不能在这个选项中添加负提示来实现你的想法。很抱歉，如果我猜对了，你能重新写你的帖子吗？

**Comment by shigma** [comment]
@MaikoTan 说的是对的，我们会增加一个 negativePrompt 的配置项来解决此问题。
