### ISSUE TITLE
关于QQ bot的发图

### ISSUE THREAD

**Issue by Young-Ginger** [koishijs/novelai-bot#67]

**Comment by Young-Ginger** [comment]
之前版本的时候的转发发图现在没有了吗，还是我遗漏了什么参数，现在的消息对于看seed来说很不方便

**Comment by shigma** [comment]
你是指现在不再转发了，还是指图没有了？

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Young-Ginger** [comment]
我指现在不再转发了

**Comment by shigma** [comment]
看看 onebot 插件是不是最新？

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Young-Ginger** [comment]
更新了 好了，谢谢解答
