### ISSUE TITLE
使用adapter-telegram作为适配器时存在问题

### ISSUE THREAD

**Issue by TeoZler** [koishijs/novelai-bot#7]
~~1.无法在群组内发送消息~~
~~笨比了，没关掉privacy mode~~
2.seed和prompt会发送多次
![BZHM{09G)W2(N6DDGP3~ T](https://user-images.githubusercontent.com/43093562/194689562-4bf00335-ec00-412b-ac65-dc9457932a24.png)

**Comment by shigma** [comment]
问题了解了，我会尽快修复。

**Comment by shigma** [comment]
最新版已修复此问题。前往插件市场更新 adapter-telegram 插件可以解决。更新方式：

1. 点击「插件市场」，搜索「telegram」
2. **查看最新版本号是否不小于 3.4.3**，如果不是，请点击右上角的刷新按钮，直到再次出现 telegram 插件
3. 选择版本为最新版本，点击对话框右下角的「更新」
4. 刷新界面，等待 Koishi 重新启动
