### ISSUE TITLE
分享两个做好的bot

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/novelai-bot#74]
开黑啦机器人：https://www.kookapp.cn/app/oauth2/authorize?id=13272&permissions=22528&client_id=PE3CLU50AFw-WT7O&redirect_uri=&scope=bot
QQ群机器人：2772315229

后端是一张3090，欢迎来玩

**Comment by MirrorCY** [comment]
也可以来我的频道试试
开黑啦 https://kook.top/6rGEDC
QQ群 767973430

**Comment by MaikoTan** [comment]
GitHub issues are used for reporting bugs, features requesting, or discussions of features / implementations.
So I would close this PR.

GitHub 议题用于报告错误、请求功能或讨论功能/实现。
所以我会关闭这个 PR。

**Comment by MirrorCY** [comment]
Shall we enable the Discussions to share our bots?

抱歉这个放在issues里好像确实不合适，所以我们能打开讨论区来分享这些吗

**Comment by shigma** [comment]
https://github.com/koishijs/novelai-bot/discussions/75

@MirrorCY
