### ISSUE TITLE
全新安装1.11.1及之后的版本时，登录方式选账号密码，会看不到email、password、allowAnlas选项

### ISSUE THREAD

**Issue by AkiraShe** [koishijs/novelai-bot#78]
如题。复现到的平台 koishi：在windows桌面版0.7.1、windwos下git拉取后新建模板项目、koishi-android v0.0.3
novelai bot 1.11.0正常，1.11.5异常。
如果是在1.11.0设置好密码等项再升级，则在1.11.1及之后的版本可以看到相应选项。

![选账号密码登录](https://user-images.githubusercontent.com/44690109/197465289-11340b95-f8c5-4475-98cb-b7054d054cd6.png)
![选令牌授权](https://user-images.githubusercontent.com/44690109/197465311-25d7d332-2c42-4104-8e65-bc5c69bf2ca0.png)

**Comment by MaikoTan** [comment]
Confirmed, the settings in "Login settings" would disappear if you choose "username" or "token". Would be fixed later.

已确认，如果你选择 "用户名 "或 "令牌"，"登录设置 "中的设置会消失。将在以后修复。

**Comment by shigma** [comment]
问题已修复，更新 console 插件到 4.6.9 可解决。

**Comment by yulongyu** [comment]
> 问题已修复，更新 console 插件到 4.6.9 可解决。

你好 我用的本地的sd，更新之后仍然没有allowAnlas选项，novelai版本1.13.3，console版本4.6.11，如何解决？无法使用img2img

**Comment by yulongyu** [comment]
> > 问题已修复，更新 console 插件到 4.6.9 可解决。
> 
> 你好 我用的本地的sd，更新之后仍然没有allowAnlas选项，novelai版本1.13.3，console版本4.6.11，如何解决？无法使用img2img
allowAnlas好像只支持授权令牌的方式，我现在用的本地sd，没有allowAnlas，但是走img2img不出图片，txt2img是正常的，日志没有有用的信息，请问怎么解决

**Comment by MaikoTan** [comment]
> > 问题已修复，更新 console 插件到 4.6.9 可解决。
> 
> 你好 我用的本地的sd，更新之后仍然没有allowAnlas选项，novelai版本1.13.3，console版本4.6.11，如何解决？无法使用img2img

Hello, the `allowAnlas` option is only for Novel AI users, since you are using the sd-webui, it is expected that you can't see the option.

If you have any other issues on sd-webui support, you can go ahead and produce a new issue.
See also: #64

你好，`allowAnlas` 选项仅适用于小说AI用户，自从你使用了 sd-webui，你看不到选项是期望的行为。

如果你对于sd-webui支持有任何其他的议题，你可以走开然后生产一个新的议题。
也可以看看：#64

**Comment by MirrorCY** [comment]
> allowAnlas好像只支持授权令牌的方式，我现在用的本地sd，没有allowAnlas，但是走img2img不出图片，txt2img是正常的，日志没有有用的信息，请问怎么解决

本地 sd 不需要 allowAnlas 选项。不出图片的报错是 500 错误吗，您使用 `http://(sdwebui)/docs#/default/img2imgapi_sdapi_v1_img2img_post` 测试一下是不是同样的错误呢

**Comment by MaikoTan** [comment]
It is not the scope of this CLOSED issue now, please open a new one.

它现在不是这个**已关闭**的议题的范围，请开启一个新的。
