### ISSUE TITLE
作者你好，能问问收录/友链事宜吗？

### ISSUE THREAD

**Issue by ShrLeeKNsword** [koishijs/novelai-bot#81]
大大你好，我是aiguidebook.top（有时在检修，无法访问，可以看我主页联系我），一个关于ai绘图的WIKI站长
我看到你选择了MIT协议
我这里缺一些教程，能问问大大愿不愿意来收录
如果不允许转载，能问问可以互加友链吗

**Comment by shigma** [comment]
您好，我们有一些兴趣，但是您的网站最近两天似乎一直打不开。

**Comment by ShrLeeKNsword** [comment]
> 您好，我们有一些兴趣，但是您的网站最近两天似乎一直打不开。

你好，网站近期转移，现在可以正常访问

**Comment by shigma** [comment]
此问题留到 discussion 讨论。
