### ISSUE TITLE
关于在QQ频道使用bot的问题

### ISSUE THREAD

**Issue by hupimaodaren** [koishijs/novelai-bot#82]
你好，我配合koishi上的adapter-qqguild插件尝试在QQ频道部署bot
无论是使用naifu还是sd-webui，bot的回复中都不带有图像
现在已知的问题是使用指令进行绘画后，QQ频道内的bot只回复：
![QQ截图20221024172705](https://user-images.githubusercontent.com/46300810/197495175-8e179616-650f-42b1-88a1-c60114782b33.png)
没有生成的图像输出
而在koishi自带的沙盒中输出为：
![微信截图_20221024172814](https://user-images.githubusercontent.com/46300810/197495372-0c9be64a-8281-444d-8de1-3eb4e7c693c0.png)
请问这种情况该如何解决呢，是否是因为输出的是base64的图像，而不是本地已生成图像的原因

**Comment by NWYLZW** [comment]
已知 bug satorijs/satori#33

**Comment by NWYLZW** [comment]
已支持待发布更新

**Comment by NWYLZW** [comment]
<img width="402" alt="484b0d1309f364b94830229fcd614fc2" src="https://user-images.githubusercontent.com/51358815/198846445-4a9a0eca-3bd3-4d5b-9f51-403feadfd128.png">

**Comment by shigma** [comment]
已支持 QQGuild 发送图片。请更新 Koishi 到最新版本 (4.9.9)，同时将 QQGuild 插件更新到最新版本 (3.3.1)。
