### ISSUE TITLE
由于base64导致图片显示不出来

### ISSUE THREAD

**Issue by ctldragon** [koishijs/novelai-bot#90]
在沙盒中和QQ中皆显示不出来图片。在浏览器改前缀可以手动显示出图片，但是QQ不行。
有什么办法能解决吗？

![image](https://user-images.githubusercontent.com/97719275/198833130-78e0cbc0-485c-42aa-8d01-9c23fc93e918.png)
![image](https://user-images.githubusercontent.com/97719275/198833190-df74db15-b87a-46fc-8503-3c43537b4496.png)
![image](https://user-images.githubusercontent.com/97719275/198833219-97e10396-06f1-416e-9981-7fd5cb7e7962.png)
![image](https://user-images.githubusercontent.com/97719275/198833256-a348efbe-6af2-4ad5-a210-f2290ee6927f.png)
![image](https://user-images.githubusercontent.com/97719275/198833297-c626f679-9f66-47ce-9719-7faa1a28cc43.png)

**Comment by shigma** [comment]
未能复现。使用的是最新版本吗？

**Comment by ctldragon** [comment]
> 未能复现。使用的是最新版本吗？

是最新版本
![image](https://user-images.githubusercontent.com/97719275/198833563-db37dd08-3eb2-4b8c-8f84-07108564fa79.png)

**Comment by ilharp** [comment]
Possible duplicate of <https://github.com/koishijs/koishi/issues/821>

Upstream bug

**Comment by ilharp** [comment]
Possible workaround: use `yarn start` to start Koishi in production mode

**Comment by shigma** [comment]
> Possible duplicate of [koishijs/koishi#821](https://github.com/koishijs/koishi/issues/821)
> 
> Upstream bug

我咋感觉不是 duplicate，那个是手动发送，这个是 bot 发的……而且那个不涉及 QQ 才对？

**Comment by ctldragon** [comment]
> Possible workaround: use to start Koishi in production mode`yarn start`



> 顺便使用的是官网还是 naifu 还是 sd-webui？

sd-webui

**Comment by ctldragon** [comment]
> Possible workaround: use to start Koishi in production mode`yarn start`

I started it with `yarn start`.

**Comment by shigma** [comment]
哦，我明白问题了，大概率是 sd-webui 有不同的 API 返回值导致的。能说明使用的是哪一版本的 sd-webui 吗？是否是 auto 的版本，以及下载的是哪个 commit？

**Comment by ctldragon** [comment]
> 哦，我明白问题了，大概率是 sd-webui 有不同的 API 返回值导致的。应该很好解决。
> 
> 能说明使用的是哪一版本的 sd-webui 吗？是否是 auto 的版本，以及下载的是哪个 commit？

https://github.com/AUTOMATIC1111/stable-diffusion-webui/

这个版本，直接 `git clone` 下来的。

**Comment by ctldragon** [comment]
开启了 `--xforners --deepbooru --api`。

**Comment by shigma** [comment]
问题已定位。auto 升级了 gradio，导致返回的图片多了一个固定前缀。

**Comment by shigma** [comment]
最新版 1.12.2 应该已经修复了此问题。感谢您的反馈。

**Comment by ctldragon** [comment]
> 最新版 1.12.2 应该已经修复了此问题。感谢您的反馈。

谢谢。
