### ISSUE TITLE
本地开发时无法配置参数。

### ISSUE THREAD

**Issue by lychees** [koishijs/novelai-bot#92]
利用 [https://koishi.js.org/manual/cli/development.html ](https://koishi.js.org/manual/cli/development.html) 构建本地插件，
进行文件替换后，在 koishi UI 里无法显示 config 信息，并且本地无法检测 config 类型导致无法调试。

**Comment by lychees** [comment]
是的。
`yarn setup`
将创建出的文件夹替换成此 repo 中的文件。
`yarn dev`
后台报错 config 类型不正确，localhost 检测不到新创建的插件。

**Comment by shigma** [comment]
类型不正确大概率是你没写对。所以具体你是怎么写的？报什么错呢？

**Comment by lychees** [comment]
我还没写，这是把这个 repo 里的文件覆盖到 `yarn setup` 创建的目录里 0.0

**Comment by shigma** [comment]
你应该意识到你说这些不能使我们帮助你解决问题，这都是大家每天在做的事情。:rofl:

请提供你目前的报错信息，如果有完整的项目更好。
