### ISSUE TITLE
增加限制tag数量功能

### ISSUE THREAD

**Issue by ai2c** [koishijs/novelai-bot#93]
一次性输入过量tag容易导致koishi卡机，希望可以添加限制tag数量的功能。

**Comment by MaikoTan** [comment]
Agreed. But the more important thing is to figure out why and how koishi crashed in this case.

同意。但更重要的是要弄清楚为什么和如何在这个案子上崩溃的恋石。

**Comment by MaikoTan** [comment]
Also, according to #63 , it looks like that koishi would only stuck if you are using the onebot platform. En plus, many other platform has message length limit (like discord limit one message only contains 2,000 characters) that is far from making koishi unresponsive.

另外，根据#63，看起来只有当你使用onebot平台时，恋石才会卡住。另外，许多其他平台都有信息长度限制（比如不和谐的限制一条信息只能包含2000个字符），这远远不能使恋石没有反应。

**Comment by shigma** [comment]
从这个角度，是否相比限制次数，更应该限制总长度呢？

**Comment by shigma** [comment]
最新版 1.13.0 已经增加 `config.maxWords` 配置项。
