### ISSUE TITLE
bug:括号转换不彻底

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/novelai-bot#96]
NovelAI-bot会转换`{`为`(`，但是似乎连续的`{{{{`会被转换为`({({`

koishi 4.9.9
koishi-plugin-novelai 1.12.6

样图：
![85NR0~VC IJ3KFU8J(PKF%M](https://user-images.githubusercontent.com/37006258/199536344-ca5e118d-f42c-4f36-a3c1-cf073a06587c.jpg)

**Comment by shigma** [comment]
感谢反馈。此问题已在最新版 1.12.7 中修复。
