### ISSUE TITLE
增加对emoji的支持

### ISSUE THREAD

**Issue by SaarChaffee** [koishijs/novelai-bot#97]
发现有人把emoji塞进了训练集，而且ai拆分不了它就只能直接用，导致效果还不错

**Comment by MaikoTan** [comment]
Is that really NovelAI and Stable Diffusion support emoji?
I thought that the AI didn't even parse the emoji itself. You see, even random words could make it not bad.

<details>
<summary>Click to Expand</summary>

![tmphhltn0nj](https://user-images.githubusercontent.com/19927330/200093546-61c08c8f-b59c-4ecd-9bf1-49b253b32fe7.png)

vjiweavn,
masterpiece, best quality
Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1776441223, Size: 512x768, Model hash: 925997e9, Clip skip: 2, ENSD: 31337

![tmp77423nkv](https://user-images.githubusercontent.com/19927330/200093582-f5deb5c8-542f-4416-a8c1-913446fec590.png)

vdsav vvlaj, vsdjva jsavv ld,
masterpiece, best quality
Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3452665919, Size: 512x768, Model hash: 925997e9, Clip skip: 2, ENSD: 31337

![tmpaxun0q7e](https://user-images.githubusercontent.com/19927330/200093687-3460c47c-036f-4407-8fc7-e11d010a5905.png)

1girl, smile,
masterpiece, best quality
Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1587429964, Size: 512x768, Model hash: 925997e9, Clip skip: 2, ENSD: 31337

![tmpc836_zh1](https://user-images.githubusercontent.com/19927330/200093707-dd8239a4-cfff-42f3-8f85-d0d3d97a80b2.png)

1girl, 😊,
masterpiece, best quality
Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3246400769, Size: 512x768, Model hash: 925997e9, Clip skip: 2, ENSD: 31337

</details>

I have only run them once, didn't even pick them. So I think the emoji does not effect at all.
If you have other opnions, feel free to comment.

**Comment by MicroCBer** [comment]
as SD is trained on laion2B-en, which is a dataset that actually contains lots of emojis, probably the emojis do have some effects, but not so large.

![image](https://user-images.githubusercontent.com/66859419/200096593-b3ffd561-96cf-4d94-a08c-f2e0a3a5fb0d.png)
![image](https://user-images.githubusercontent.com/66859419/200096611-046e4cd2-d4d4-4b75-9689-02646345946e.png)
![image](https://user-images.githubusercontent.com/66859419/200096671-80c9bb00-0bee-4d87-b8df-3fe243c7f9ab.png)

but even Chinese characters have an influence on the result, so I'm not pretty sure actually.

**Comment by MaikoTan** [comment]
I do know that some ascii-based emojis effect on NovelAI, as they are really tags on danbooru.
for example, `:p` refers to tongue out
 ![file-13.jpg](https://user-images.githubusercontent.com/19927330/200097102-d57d5ff2-b12b-4601-a5e9-c4e329f0d40e.jpg)

black frilled swimsuit, hair bow, 1girl, :p, masterpiece, best quality
Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry
Steps: 28, Sampler: Euler a, CFG scale: 11, Seed: 1065624717, Size: 512x768, Model hash: e6e8e1fc, Seed resize from: -1x-1, Denoising strength: 0.75, Clip skip: 2, ENSD: 31337

**Comment by MicroCBer** [comment]
also, with some emojis (e.g. 🟦) in the prompt, even small changes in the CFG Scale can lead to a completely different result, while other emojis (e.g. 🐈) aren't. 

and SD seems really knows what emojis mean (well, at least some of them).

![image](https://user-images.githubusercontent.com/66859419/200097149-d2d5a4d0-65b3-4bb6-b025-001aa0f0bccb.png)
![image](https://user-images.githubusercontent.com/66859419/200097127-ca95a2e9-7e6a-4751-a72f-9d34f6e57d03.png)

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/200097216-902857af-b1ac-4e8c-989a-0517c125e062.png)
![image](https://user-images.githubusercontent.com/66859419/200097225-e7c18e99-42b7-4507-8576-60dde4338caf.png)

and idk if it just can't understand these or it's just because the messy dataset leads to a misunderstanding. anyway, emoji support seems to be necessary then.

**Comment by SaarChaffee** [comment]
补充：
在11月2号，大魔导书之一的[元素同典](https://docs.qq.com/doc/DWFdSTHJtQWRzYk9k)得出过关于各类emoji的结论
即：
一、无法被sd拆分。emoji本身作为单个字符，sd是无法尝试将其拆分开来的，以最短字符代表出一个概念
二、信息密度高。emoji是包含复数个低阶语法（单词）的高阶形式，能表达出大于等于一个单词的内容

**Comment by MaikoTan** [comment]
Looks like it is even more black-box-ish than sd itself...
Well, we can make it read by sd-webui, but how about NovelAI or NAIFU?

**Comment by MicroCBer** [comment]
I don't use naifu, u can test it on it xD. but I can't see how novelai backend doesn't support emojis.

the prompt and seed I used are included in the screenshots in the comments above by me.

**Comment by MaikoTan** [comment]
Re: chinese characters
There ARE some reporting showing that some concept in Chinese would be better than english. For example some traditional Chinese clothes or orgaments.

Also some Japanese words. Like `幼稚園児` sometimes better than `female child` or `loli` if you want to make character much younger, as well as `かわいい` vs `adorable` or `cute`.

**Comment by MicroCBer** [comment]
> Re: chinese characters There ARE some reporting showing that some concept in Chinese would be better than english. For example some traditional Chinese clothes or orgaments.
> 
> Also some Japanese words. Like `幼稚園児` sometimes better than `female child` or `loli` if you want to make character much younger, as well as `かわいい` vs `adorable` or `cute`.

Probably Chinese should also be allowed then, but we need a way to make sure if the **user**(I mean who is using the bot, not who maintains the bot) knows what he's doing.

**Comment by shigma** [comment]
最新版 1.13.1 默认情况下已经接受 emoji 了，可通过 `config.latinOnly` 回到过去的模式。
