### ISSUE TITLE
Bug: basePrompt默认附加在最末尾导致生成结果不理想

### ISSUE THREAD

**Issue by w123456w30w** [koishijs/novelai-bot#99]
### Describe the bug

也许不是bug，观察到basePrompt会自动附加在Prompt末尾
例如提交了单个角色prompt，期望传递到后端的是
“masterpiece, best quality, 角色prompt”
实际传递为
"角色prompt, masterpiece, best quality"

### Steps to reproduce

例如提交了单个角色prompt，实际传递至后端的为
"角色prompt, masterpiece, best quality"

### Expected behavior

期望传递到后端的是
“masterpiece, best quality, 角色prompt”

### Launcher

Containers (Docker, Kubernates, etc)

### Backend

NAIFU

### Versions

- OS: Unraid
- Adapter: OneBot
- Node version: Docker
- Koishi version: 4.10.0

**Comment by MaikoTan** [comment]
Bonjour, @w123456w30w !
Merci beaucoup pour ton bon issue !
Mais le comportement actuel est attendu, ce n'est pas un bug.
Dans la plupart des cas, les descriptions textuelles ajouté à l'avant ne serait pas performant s'il allait en dernier. C'est pourquoi nous procédons au changement.
Notre but n'est pas de répliquer à 100% comme IA Novel, mais de générer de bons images.

N'hésitez pas à écrire votre commentaire!

------

你好， @w123456w30w ！
非常感谢你的好议题！
但是这个行为实际上是期望的，这不是一个错误。
在很多的情境中，添加在前面的文本描述相比放在后面没有更好。这是为什么我们做了这样的改动。
我们的目标不是 100% 复现 IA Novel 的，而是生成好的图片。

不要犹豫写下你的评论！

**Comment by MirrorCY** [comment]
NovelAi 网站的方案是将 masterpiece, best quality 放在参数最前的，所以这个意见值得考虑。

**Comment by MaikoTan** [comment]
Eh, il est possible d'ajouter une nouvelle option qui vous permet d'ajouter les descriptions textuelles de base à l'avant ou à l'arrière de les descriptions textuelles.

嗯，可以添加一个新选项，允许您将基本文本描述添加到文本描述的前面或后面。

**Comment by shigma** [comment]
最新版本 1.13.2 支持了 `config.placement` 配置项，可用于调整默认 prompt 的附加位置。

**Comment by MaikoTan** [comment]
Super !
merci Shigma, pour votre solution rapide.

太棒了！
謝謝你，夢夢。為了你的快速修復。
